/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoConsultaGarantiaCliente;
import inventory.acceso.AccesoExcepciones;
import inventory.acceso.AccesoInventario;
import inventory.acceso.AccesoSucursal;
import inventory.objetos.ObjetosConsultaGarantiaCliente;
import inventory.objetos.ObjetosSucursal;
import java.awt.Dimension;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author FERNANDO
 */
public class wdwBaseDeDatosHistorialGarantiaCliente extends javax.swing.JInternalFrame {

    private AccesoConsultaGarantiaCliente ctrl_consulta = new AccesoConsultaGarantiaCliente();
    private ObjetosConsultaGarantiaCliente objeto = new ObjetosConsultaGarantiaCliente();
    private AccesoExcepciones mensaje = new AccesoExcepciones();

    /**
     * Creates new form wdwBaseDeDatosHistorialGarantiaCliente
     */
    public wdwBaseDeDatosHistorialGarantiaCliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModifica = new javax.swing.JPanel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaGarantia = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        lblBuscar1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtFechaInicial = new com.toedter.calendar.JDateChooser();
        lblFecha = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        txtFechaFinal = new com.toedter.calendar.JDateChooser();
        btnFactura = new javax.swing.JButton();
        txtBuscarSerie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarSerie = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Historial de Garantia Cliente");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/historialGarantiaCliente.png"))); // NOI18N

        panelModifica.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scrollTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaGarantia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "ID producto", "Marca", "Serie Recibida", "Serie Entregada", "ID serie", "Nit", "Cliente", "Falla", "Comentario", "Observaciones", "Fecha Registro", "ID factura"
            }
        ));
        tablaGarantia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetalleOnClick(evt);
            }
        });
        scrollTabla.setViewportView(tablaGarantia);

        javax.swing.GroupLayout panelModificaLayout = new javax.swing.GroupLayout(panelModifica);
        panelModifica.setLayout(panelModificaLayout);
        panelModificaLayout.setHorizontalGroup(
            panelModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelModificaLayout.setVerticalGroup(
            panelModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar1.setText("ID Garantía");

        txtBuscar.setBackground(new java.awt.Color(255, 255, 204));
        txtBuscar.setToolTipText("Ingrese el nombre del empleado a buscar");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtFechaInicial.setBackground(new java.awt.Color(240, 240, 204));
        txtFechaInicial.setToolTipText("Ingrese la Fecha Inicial.");
        txtFechaInicial.setDateFormatString("yyyy-MM-dd");
        txtFechaInicial.setMaximumSize(new java.awt.Dimension(120, 20));
        txtFechaInicial.setMinimumSize(new java.awt.Dimension(120, 20));
        txtFechaInicial.setPreferredSize(new java.awt.Dimension(120, 20));

        lblFecha.setText("Desde");

        lblHasta.setText("Hasta");

        txtFechaFinal.setBackground(new java.awt.Color(240, 240, 204));
        txtFechaFinal.setToolTipText("Ingrese la Fecha Final.");
        txtFechaFinal.setDateFormatString("yyyy-MM-dd");
        txtFechaFinal.setMaximumSize(new java.awt.Dimension(120, 20));
        txtFechaFinal.setMinimumSize(new java.awt.Dimension(120, 20));
        txtFechaFinal.setPreferredSize(new java.awt.Dimension(120, 20));

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonImpresoraLaser.png"))); // NOI18N
        btnFactura.setToolTipText("Imprimir Factura");
        btnFactura.setActionCommand("imprimirEnvio");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        jLabel1.setText("Serie");

        btnMostrarSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnMostrarSerie.setText("Buscar");
        btnMostrarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(lblHasta)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnMostrarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar1)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaInicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarSerie)
                            .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(btnMostrarSerie)))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.llenarTablaFecha();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed

        //ejecución del repote seleccionado
        try {

            AccesoInventario acceso_inventario = new AccesoInventario();
            AccesoSucursal acceso_sucursal = new AccesoSucursal();
            ObjetosSucursal objeto_sucursal = new ObjetosSucursal();

            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptGarantiaCliente.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();

            //parametros generales del encabezado
            objeto_sucursal = acceso_sucursal.buscarSucursales(1, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

            //parametros del reporte
            parametro.put("P_DIRECCION_SUCURSAL", objeto_sucursal.getDireccion_sucursal());
            parametro.put("P_NIT", objeto_sucursal.getNit_sucursal());
            parametro.put("P_NOMBRE_EMPRESA", objeto_sucursal.getNombre_sucursal());
            parametro.put("P_SUCURSAL", objeto_sucursal.getDescripcion_sucursal());
            parametro.put("P_TELEFONO", objeto_sucursal.getTelefonos_sucursal());

            //parametro de busqueda
            parametro.put("P_ID_GARANTIA", Integer.parseInt(txtBuscar.getText().trim()));

            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso_inventario.conectar());
            JInternalFrame ventana = new JInternalFrame("Inventory 3.0");
            ventana.getContentPane().add(new JRViewer(pantalla));
            ventana.setPreferredSize(new Dimension(900, 500));
            ventana.setClosable(true);
            ventana.setMaximizable(true);
            ventana.setResizable(true);
            ventana.setVisible(true);
            ventana.pack();

            int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
            int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
            int x = (ancho - ventana.getWidth()) / 2;
            int y = (alto - ventana.getHeight() - 100) / 2;

            Inventory.pnlPrincipal.add(ventana);

            ventana.setLocation(x, y);
            ventana.setVisible(true);
            ventana.toFront();

        } catch (JRException error) {
            mensaje.manipulacionExcepciones("critico", error.getMessage(), "Reporte de Garantia Cliente");
        }
        
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void tablaDetalleOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleOnClick
        txtBuscar.setText(tablaGarantia.getValueAt(tablaGarantia.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tablaDetalleOnClick

    private void btnMostrarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSerieActionPerformed
        llenarTablaSerie();
    }//GEN-LAST:event_btnMostrarSerieActionPerformed

    private void llenarTablaFecha() {
        
        ArrayList<ObjetosConsultaGarantiaCliente> lista = new ArrayList<>();

        DefaultTableModel tablaModelo = new DefaultTableModel();
        tablaModelo.addColumn("ID");
        tablaModelo.addColumn("Producto");
        tablaModelo.addColumn("ID producto");
        tablaModelo.addColumn("Marca");
        tablaModelo.addColumn("Serie Recibida");
        tablaModelo.addColumn("Serie Entregada");
        tablaModelo.addColumn("Nit");
        tablaModelo.addColumn("Cliente");
        tablaModelo.addColumn("Falla");
        tablaModelo.addColumn("Comentario");
        tablaModelo.addColumn("Fecha Registro");
        tablaModelo.addColumn("ID factura");
        tablaModelo.addColumn("Observaciones");
        
        int fila = 0;
        int linea = 1;
        
        try {
            
            lista = ctrl_consulta.buscarReclamoFecha(this.obtenerFechaI(), this.obtenerFechaF(),
                    Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            
            if (lista.isEmpty()) {
                mensaje.manipulacionExcepciones("critico", "No hay resultados", "sin resultados");
            } else {
                for (ObjetosConsultaGarantiaCliente datos : lista) {
                    tablaModelo.setRowCount(linea);
                    tablaModelo.setValueAt(datos.getIdReclamo(), fila, 0);
                    tablaModelo.setValueAt(datos.getProducto(), fila, 1);
                    tablaModelo.setValueAt(datos.getIdProducto(), fila, 2);
                    tablaModelo.setValueAt(datos.getMarca(), fila, 3);
                    tablaModelo.setValueAt(datos.getSerie(), fila, 4);
                    tablaModelo.setValueAt(datos.getSerieEntregada(), fila, 5);
                    tablaModelo.setValueAt(datos.getNit(), fila, 6);
                    tablaModelo.setValueAt(datos.getCliente(), fila, 7);
                    tablaModelo.setValueAt(datos.getFalla(), fila, 8);
                    tablaModelo.setValueAt(datos.getComentario(), fila, 9);
                    tablaModelo.setValueAt(datos.getFechaReclamo(), fila, 10);
                    tablaModelo.setValueAt(datos.getIdFactura(), fila, 11);
                    tablaModelo.setValueAt(datos.getObservaciones(), fila, 12);
                    fila++;
                    linea++;

                }

                this.tablaGarantia.setModel(tablaModelo);
            }
        } catch (Exception e) {

        }

    }
    
    private void llenarTablaSerie() {
        
        ArrayList<ObjetosConsultaGarantiaCliente> lista = new ArrayList();

        DefaultTableModel tablaModelo = new DefaultTableModel();
        tablaModelo.addColumn("ID");
        tablaModelo.addColumn("Producto");
        tablaModelo.addColumn("ID producto");
        tablaModelo.addColumn("Marca");
        tablaModelo.addColumn("Serie Recibida");
        tablaModelo.addColumn("Serie Entregada");
        tablaModelo.addColumn("Nit");
        tablaModelo.addColumn("Cliente");
        tablaModelo.addColumn("Falla");
        tablaModelo.addColumn("Comentario");
        tablaModelo.addColumn("Fecha Registro");
        tablaModelo.addColumn("ID factura");
        tablaModelo.addColumn("Observaciones");
        
        int fila = 0;
        int linea = 1;
        
        try {
            
            lista = ctrl_consulta.buscarReclamoSerie(this.txtBuscarSerie.getText().trim().replaceAll("'", "´"),Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            
            if (lista.isEmpty()) {
                mensaje.manipulacionExcepciones("critico", "No hay resultados", "sin resultados");
            } else {
                for (ObjetosConsultaGarantiaCliente datos : lista) {
                    tablaModelo.setRowCount(linea);
                    tablaModelo.setValueAt(datos.getIdReclamo(), fila, 0);
                    tablaModelo.setValueAt(datos.getProducto(), fila, 1);
                    tablaModelo.setValueAt(datos.getIdProducto(), fila, 2);
                    tablaModelo.setValueAt(datos.getMarca(), fila, 3);
                    tablaModelo.setValueAt(datos.getSerie(), fila, 4);
                    tablaModelo.setValueAt(datos.getSerieEntregada(), fila, 5);
                    tablaModelo.setValueAt(datos.getNit(), fila, 6);
                    tablaModelo.setValueAt(datos.getCliente(), fila, 7);
                    tablaModelo.setValueAt(datos.getFalla(), fila, 8);
                    tablaModelo.setValueAt(datos.getComentario(), fila, 9);
                    tablaModelo.setValueAt(datos.getFechaReclamo(), fila, 10);
                    tablaModelo.setValueAt(datos.getIdFactura(), fila, 11);
                    tablaModelo.setValueAt(datos.getObservaciones(), fila, 12);
                    fila++;
                    linea++;

                }

                this.tablaGarantia.setModel(tablaModelo);
            }
        } catch (Exception e) {

        }

    }

    private void llenarTablaId() {
        ArrayList<ObjetosConsultaGarantiaCliente> lista = new ArrayList();

        DefaultTableModel tablaModelo = new DefaultTableModel();
        tablaModelo.addColumn("ID");
        tablaModelo.addColumn("Producto");
        tablaModelo.addColumn("ID producto");
        tablaModelo.addColumn("Marca");
        tablaModelo.addColumn("Serie Recibida");
        tablaModelo.addColumn("Serie Entregada");
        tablaModelo.addColumn("Nit");
        tablaModelo.addColumn("Cliente");
        tablaModelo.addColumn("Falla");
        tablaModelo.addColumn("Comentario");
        tablaModelo.addColumn("Fecha Registro");
        tablaModelo.addColumn("ID factura");
        tablaModelo.addColumn("Observaciones");
        int fila = 0;
        int linea = 1;
        try {
            lista = ctrl_consulta.buscarReclamoId(this.txtBuscar.getText(),
                    Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            if (lista.isEmpty()) {
                mensaje.manipulacionExcepciones("critico", "No hay resultados", "sin resultados");
            } else {
                for (ObjetosConsultaGarantiaCliente datos : lista) {
                    tablaModelo.setRowCount(linea);

                    tablaModelo.setValueAt(datos.getIdReclamo(), fila, 0);
                    tablaModelo.setValueAt(datos.getProducto(), fila, 1);
                    tablaModelo.setValueAt(datos.getIdProducto(), fila, 2);
                    tablaModelo.setValueAt(datos.getMarca(), fila, 3);
                    tablaModelo.setValueAt(datos.getSerie(), fila, 4);
                    tablaModelo.setValueAt(datos.getSerieEntregada(), fila, 5);
                    tablaModelo.setValueAt(datos.getNit(), fila, 6);
                    tablaModelo.setValueAt(datos.getCliente(), fila, 7);
                    tablaModelo.setValueAt(datos.getFalla(), fila, 8);
                    tablaModelo.setValueAt(datos.getComentario(), fila, 9);
                    tablaModelo.setValueAt(datos.getFechaReclamo(), fila, 10);
                    tablaModelo.setValueAt(datos.getIdFactura(), fila, 11);
                    tablaModelo.setValueAt(datos.getObservaciones(), fila, 12);
                    fila++;
                    linea++;

                }

                this.tablaGarantia.setModel(tablaModelo);
            }
        } catch (Exception e) {

        }

    }

    private String obtenerFechaI() {
        try {
            Date date = this.txtFechaInicial.getDate();
            String fecha = new SimpleDateFormat("YYYY-MM-dd").format(date);
            return String.valueOf(fecha);
        } catch (NullPointerException ex) {
            return null;
        }
    }

    private String obtenerFechaF() {
        try {
            Date date = this.txtFechaFinal.getDate();
            String fecha = new SimpleDateFormat("YYYY-MM-dd").format(date);
            return String.valueOf(fecha);
        } catch (NullPointerException ex) {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnMostrarSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBuscar1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JPanel panelModifica;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaGarantia;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarSerie;
    private com.toedter.calendar.JDateChooser txtFechaFinal;
    private com.toedter.calendar.JDateChooser txtFechaInicial;
    // End of variables declaration//GEN-END:variables
}
