package inventory.vistas;

import inventory.acceso.*;
import inventory.objetos.ObjetosLoggin;
import inventory.objetos.ObjetosTerminal;
import inventory.objetos.ObjetosUsuario;
import java.io.IOException;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

public class wdwIngresoDeUsuario extends javax.swing.JInternalFrame {
    
    private String UsuarioLogeado = null;
    private String MacAdress = null;
    private String vUsuario = null;
    private String version = "0";
    private String ReportesDeVentas = "NO";
    private String PantallaVentasActivas = "NO";
    private String PantallaProveedores = "NO";
    private boolean ver_reportes_ventas;
    private AccesoTerminal Terminal = new AccesoTerminal();
    private AccesoUsuario Usuario = new AccesoUsuario();
    private AccesoArchivo Archivo = new AccesoArchivo();
    
    private AccesoExcepciones Mensaje = new AccesoExcepciones();
    private ObjetosLoggin Loggin = new ObjetosLoggin();
    private AccesoLoggin NuevoLoggin = new AccesoLoggin();
    
    
    public wdwIngresoDeUsuario() {
        initComponents();
        MacAdress = obeterMACAdress();
        System.out.println(MacAdress);
    }

    public String obeterMACAdress() {
        
        NetworkInterface a;
        String valor = "";
        
        try {
            
            a = NetworkInterface.getByInetAddress(InetAddress.getLocalHost());
            byte[] mac = a.getHardwareAddress();

            StringBuilder sb = new StringBuilder();
            
            for (int i = 0; i < mac.length; i++) {
                sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));
            }

            valor = sb.toString();

        } catch (UnknownHostException | SocketException e) {
            Mensaje.manipulacionExcepciones("critico", "No se pudo obterner la direccion de la PC.", "Obtener MAC Adress");
        }

        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingreso de Usuario");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgLogoSistema.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(300, 210));
        setMinimumSize(new java.awt.Dimension(300, 210));
        setPreferredSize(new java.awt.Dimension(300, 210));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonAceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonCancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setText("Usuario");

        txtUsuario.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Usuario </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/imgTooltipMessage.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingrese el nombre de usuario, el sistema reconocera "
            + "tanto mayusculas como minusculas."
            + "</td></tr> <table> </html>");

        lblClave.setText("Clave");

        txtContrasenia.setToolTipText("<html> <table width=\"200px\" height=\"75px\">"
            + "<tr bgcolor=\"#FE642E\">"
            + "<td font color=\"#FFFFFF\">"
            + "<h2> Contraseña </h2>"
            + "</td>"
            + "<img src=\"" + this.getClass().getResource("/inventory/imagenes/imgTooltipMessage.png") + "\" />"
            + "<td>"
            + "</td"
            + "</tr colspan=\"2\">"
            + "<tr><td>"
            + "Ingrese la contraseña proporcionada por el administrador."
            + "</td></tr> <table> </html>");
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseniaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblClave))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtContrasenia))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 72, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtUsuario.setText("");
        txtContrasenia.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comprobarUsuario() {
        
        try {
            version = Archivo.leer("[Version]");
        } catch (IOException Error) {
            System.out.println(Error.toString());
            Mensaje.manipulacionExcepciones("critico", "No encontro configuracion Version.", "Versión del sistema");
        }
        
        try {
            ReportesDeVentas = Archivo.leer("[ReportesDeVentas]");
        } catch (IOException Error) {
            System.out.println(Error.toString());
            Mensaje.manipulacionExcepciones("critico", "No encontro configuracion Reporte de Ventas.", "Versión del sistema");
        }
        
        try {
            PantallaVentasActivas = Archivo.leer("[PantallaVentasActivas]");
        } catch (IOException Error) {
            System.out.println(Error.toString());
            Mensaje.manipulacionExcepciones("critico", "No encontro configuracion Ventas Activas.", "Versión del sistema");
        }
        
        try {
            PantallaProveedores = Archivo.leer("[PantallaProveedores]");
            System.out.println(PantallaProveedores);
        } catch (IOException Error) {
            System.out.println(Error.toString());
            Mensaje.manipulacionExcepciones("critico", "No encontro configuracion Proveedores.", "Versión del sistema");
        }

        System.out.println("Validar version");
        if (version.equals("2010")) {
            System.out.println("Versión básica");
            mostrarVersionBasica();
        } else {
            if (version.equals("2020")) {
                System.out.println("Versión completa");
                mostrarVersionCompleta();
            } else {
                Mensaje.manipulacionExcepciones("critico", "La versión configurada no existe.", "Versión del sistema");
            }
        }

    }
    
    private void mostrarVersionBasica() {
        
        AccesoTerminal terminal = new AccesoTerminal();
        AccesoUsuario acceso = new AccesoUsuario();

        ArrayList<ObjetosUsuario> usuarios = acceso.validaCredenciales(txtUsuario.getText(), txtContrasenia.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        ArrayList<ObjetosTerminal> lista_terminal = Terminal.validarLicencia(MacAdress, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

        String rol = "";
        String mac = "";
        
        //Obtener parametro para validar
        //si se requiere mac adrress
        try {
            mac = Archivo.leer("[Mac]");
        } catch(Exception exception) {
            Mensaje.manipulacionExcepciones("critico", "No se pudo leer el archivo de configuraciones para la Macaddress", "Lectura Archivo");
        }
        
        
        if (usuarios.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "El nombre de usuario o clave es incorrecto.", "Comprobar Usuario");
        } else {

            if (usuarios.size() > 1) {

                Mensaje.manipulacionExcepciones("critico", "Este Usuario esta repetido por favor verifique.", "Comprobar Usuario");

            } else {

                if (lista_terminal.size() == 1 || mac.equals("FALSE")) {
                    
                    if(mac.equals("FALSE")) {
                        Inventory.lblTerminal.setText("1");
                    }

                    for (ObjetosUsuario x : usuarios) {

                        Inventory.lblUsuario.setText(x.getNombre_usuario());
                        Inventory.lblRol.setText(x.getTipo_usuario());
                        Inventory.lblNombre.setText(x.getNombre_empleado());
                        Inventory.lblSucursal.setText(x.getNombre_sucursal());

                        //Inventory.menuUsuario.setText(x.getNombre_usuario());
                        rol = x.getTipo_usuario();
                        
                        if (x.getTipo_usuario().equals("Administrador")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false);  //COMPLETA
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            
                            Inventory.menu.setVisible(true);
                            
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuAbonoProveedores.setVisible(false); //COMPLETA
                            Inventory.menuIntercambiarSerie.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false); //COMPLETA
                            Inventory.menuAbonoDeClientes.setVisible(false); //COMPLETA
                            Inventory.menuAnticipo.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoTaller.setVisible(false); //COMPLETA
                            
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false); //COMPLETA
                            
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuReportesAbonosDetalle.setVisible(false);
                            Inventory.menuReportesDetalleAbonosProveedor.setVisible(false);
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL
                            
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(false); //COMPLETA
                            
                            Inventory.menuUsuarios.setVisible(true);
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false); //COMPLETA

                            Inventory.btnFacturaCliente.setVisible(false); //COMPLETA
                            Inventory.btnFacturasProveedor.setVisible(false); //COMPLETA
                            Inventory.btnGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.btnGarantiaProveedor.setVisible(false); //COMPLETA
                            Inventory.btnReparaciones.setVisible(false); //COMPLETA
                            Inventory.btnAnticipos.setVisible(false); //COMPLETA
                            Inventory.btnActualizar.setVisible(false); //COMPLETA

                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Jefe Sucursal")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false); //COMPLETA
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);

                            Inventory.menu.setVisible(true);
                            
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuAbonoProveedores.setVisible(false); //COMPLETA
                            Inventory.menuIntercambiarSerie.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false); //COMPLETA
                            Inventory.menuAbonoDeClientes.setVisible(false); //COMPLETA
                            Inventory.menuAnticipo.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoTaller.setVisible(false); //COMPLETA
                            
                            
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false); //COMPLETA
                            
                            // Reportes
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuReportesAbonosDetalle.setVisible(false); //COMPLETA
                            Inventory.menuReportesDetalleAbonosProveedor.setVisible(false); //COMPLETA
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL
                            
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(false); //COMPLETA
                            
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantia.setVisible(false); //COMPLETA
                            
                            //Permisos para los movimientos
                            //Inventory.menuMovimientoCompras.setVisible(false);

                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Secretaria")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(false);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false);
                            Inventory.btnAccesoVentaDeProductos.setVisible(false);
                            Inventory.btnAccesoConsultaProductos.setVisible(false);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(false);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuVentaDeProductos.setVisible(false);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(false);
                            Inventory.menuCierreDeCaja.setVisible(false);
                            Inventory.menuAnulacionVentas.setVisible(false);
                            Inventory.menuAbonoDeClientes.setVisible(false);
                            Inventory.menuAnticipo.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);

                            //Items menu catalogos
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(true);
                            Inventory.sepMenuCatalogoUno.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuConsultaProductos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuSeries.setVisible(false);
                            Inventory.menuMarcas.setVisible(false);
                            
                            //menu reportes
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);

                            this.dispose();

                        }
                        
                        if (x.getTipo_usuario().equals("Cajero")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(false);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false);
                            Inventory.btnAccesoVentaDeProductos.setVisible(false);
                            Inventory.btnAccesoConsultaProductos.setVisible(false);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(false);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(false);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuVentaDeProductos.setVisible(false);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            Inventory.menuAnulacionVentas.setVisible(true);
                            Inventory.menuAbonoDeClientes.setVisible(false); //COMPLETA
                            Inventory.menuAnticipo.setVisible(false); //COMPLETA
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            
                            //Items menu catalogos
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuConsultaProductos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(false); // Menu Usuarios
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            // Reportes
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuReportesAbonosDetalle.setVisible(false); //COMPLETA
                            Inventory.menuReportesDetalleAbonosProveedor.setVisible(false); //COMPLETA
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL

                            this.dispose();

                        }
                        
                        if (x.getTipo_usuario().equals("Tecnico")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(false);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false); //COMPLETA
                            Inventory.btnAccesoVentaDeProductos.setVisible(false);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);

                            // Items del menu principal
                            Inventory.menu.setVisible(false); //COMPLETA
                            Inventory.menuMovimiento.setVisible(false); //COMPLETA
                            Inventory.menuCatalogo.setVisible(false);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(false);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(false); //COMPLETA

                            // Items del menu movimientos
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuVentaDeProductos.setVisible(false);
                            Inventory.menuProforma.setVisible(false);
                            Inventory.menuVentasActivas.setVisible(false);
                            Inventory.menuCierreDeCaja.setVisible(false);
                            Inventory.menuAnulacionVentas.setVisible(false);
                            Inventory.menuAbonoDeClientes.setVisible(false);
                            Inventory.menuAnticipo.setVisible(false);
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false);

                            //Items menu catalogos
                            Inventory.menuClientes.setVisible(false);
                            Inventory.menuProveedores.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuConsultaProductos.setVisible(false); //COMPLETA
                            Inventory.menuUsuarios.setVisible(false); 
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            //Menu de base de datos
                            Inventory.menuBaseDeDatos.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(false);
                            Inventory.menuExportarCatalogoDeProductos.setVisible(false);
                            Inventory.menuImportarCatalogoDeProductos.setVisible(false);
                            Inventory.sepExportar.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeCompras.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeVentas.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeProforma.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialTraslado.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(false);

                            
                            // Reportes
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuReportesAbonosDetalle.setVisible(false); //COMPLETA
                            Inventory.menuReportesDetalleAbonosProveedor.setVisible(false); //COMPLETA
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL
                            
                            this.dispose();

                        }
                        
                        if (x.getTipo_usuario().equals("Vendedor")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false); //COMPLETA
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            // Sub menu Compras
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            
                            // Sub menu Garantias
                            Inventory.menuMovimientoGarantia.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false); //COMPLETA
                            
                            // Sub menu Inventario
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuTraslado.setVisible(true);
                            
                            // Sub menu Ventas
                            Inventory.menuVentaDeProductos.setVisible(true);
                            Inventory.menuAbonoDeClientes.setVisible(false); //COMPLETA
                            Inventory.menuAnulacionVentas.setVisible(false);
                            Inventory.menuAnticipo.setVisible(false); //COMPLETA
                            Inventory.menuCierreDeCaja.setVisible(true);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            
                            // Sub menu Taller
                            Inventory.menuOrdenDeServicio.setVisible(false); //COMPLETA
                            
                            //Items menu catalogos
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuMarcas.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuSeries.setVisible(false); //COMPLETA
                            Inventory.menuConsultaProductos.setVisible(true);
                            
                            Inventory.sepMenuCatalogoUno.setVisible(false);
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            Inventory.sepMenuCatalogoDos.setVisible(true);
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(true);
                            
                            //Reportes
                            Inventory.menuComisiones.setVisible(false);
                            Inventory.menuCompras.setVisible(false);
                            Inventory.menuVentas.setVisible(true);
                            Inventory.menuInventario.setVisible(false);
                            Inventory.menuReportesDetalleGanancia.setVisible(false);
                            Inventory.menuReportesAbonosDetalle.setVisible(false); //COMPLETA
                            Inventory.menuReportesDetalleAbonosProveedor.setVisible(false); //COMPLETA
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL
                            
                            //Base de datos
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuExportarCatalogoDeProductos.setVisible(false);
                            Inventory.menuImportarCatalogoDeProductos.setVisible(false);
                            Inventory.sepExportar.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialDeCompras.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeVentas.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialDeProforma.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialTraslado.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(false); //COMPLETA
                            
                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Encargado")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false); //COMPLETA
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            // Sub menu Compras
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            
                            // Sub menu Garantias
                            Inventory.menuMovimientoGarantia.setVisible(false); //COMPLETA
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false); //COMPLETA
                            
                            // Sub menu Inventario
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuTraslado.setVisible(true);
                            
                            // Sub menu Ventas
                            Inventory.menuVentaDeProductos.setVisible(true);
                            Inventory.menuAbonoDeClientes.setVisible(false); //COMPLETA
                            Inventory.menuAnulacionVentas.setVisible(true);
                            Inventory.menuAnticipo.setVisible(false); //COMPLETA
                            Inventory.menuCierreDeCaja.setVisible(true);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            
                            // Sub menu Taller
                            Inventory.menuOrdenDeServicio.setVisible(false); //COMPLETA
                            
                            //Items menu catalogos
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuMarcas.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuSeries.setVisible(false); //COMPLETA
                            Inventory.menuConsultaProductos.setVisible(true);
                            
                            Inventory.sepMenuCatalogoUno.setVisible(false);
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            Inventory.sepMenuCatalogoDos.setVisible(true);
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(true);
                            
                            //Reportes
                            Inventory.menuComisiones.setVisible(false);
                            Inventory.menuCompras.setVisible(false);
                            Inventory.menuVentas.setVisible(true);
                            Inventory.menuInventario.setVisible(false);
                            Inventory.menuReportesDetalleGanancia.setVisible(false);
                            Inventory.menuReportesAbonosDetalle.setVisible(false); //COMPLETA
                            Inventory.menuReportesDetalleAbonosProveedor.setVisible(false); //COMPLETA
                            Inventory.menuReportesVentasPorFechaFEL.setVisible(false); //FEL
                            Inventory.menuReportesVentasPorFechaSinFEL.setVisible(false); //FEL
                            
                            //Base de datos
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuExportarCatalogoDeProductos.setVisible(false);
                            Inventory.menuImportarCatalogoDeProductos.setVisible(false);
                            Inventory.sepExportar.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialDeCompras.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeVentas.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialDeProforma.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialTraslado.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(false); //COMPLETA
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(false); //COMPLETA
                            
                            this.dispose();

                        }
                        
                    }
                    
                    //habilitar pantalla de Log
                    try {
                        if(Archivo.leer("[LOG]").equals("TRUE")) {
                            Inventory.pnlLog.setVisible(true);
                        }
                    } catch (Exception Error) {
                        System.out.println("Error al activar el Log.");
                    }

                    //colocar el nombre de la terminal en la pantalla principal
                    Inventory.lblTerminal.setText(String.valueOf(lista_terminal.listIterator(0).next().getId_terminal()));
                    
                    //Colocar el fondo del usuario en la pantalla principal
                    Inventory.definirFondoUsuario();

                } else {

                    Mensaje.manipulacionExcepciones("critico", "El equiopo " + MacAdress + " no cuenta con licencia de uso.", "Comprobar Usuario");

                }

            }
        }

        txtContrasenia.setText("");
        txtUsuario.setText("");
        txtUsuario.requestFocus();
    }
    
    private void mostrarVersionCompleta() {
        
        AccesoTerminal terminal = new AccesoTerminal();
        AccesoUsuario acceso = new AccesoUsuario();

        System.out.println("Validar credenciales");
        ArrayList<ObjetosUsuario> usuarios = acceso.validaCredenciales(txtUsuario.getText(), txtContrasenia.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        System.out.println("Validar licencia");
        ArrayList<ObjetosTerminal> lista_terminal = Terminal.validarLicencia(MacAdress, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

        String rol = "";
        String mac = "";
        
        try {
            mac = Archivo.leer("[Mac]");
        } catch(Exception exception) {
            Mensaje.manipulacionExcepciones("critico", "No se pudo leer el archivo de configuraciones para la Macaddress", "Lectura Archivo");
        }
        
        
        if (usuarios.isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "El nombre de usuario o clave es incorrecto.", "Comprobar Usuario");
        } else {

            if (usuarios.size() > 1) {

                Mensaje.manipulacionExcepciones("critico", "Este Usuario esta repetido por favor verifique.", "Comprobar Usuario");

            } else {

                if (lista_terminal.size() == 1 || mac.equals("FALSE")) {
                    
                    if(mac.equals("FALSE")) {
                        Inventory.lblTerminal.setText("1");
                    }

                    for (ObjetosUsuario x : usuarios) {

                        Inventory.lblUsuario.setText(x.getNombre_usuario());
                        Inventory.lblRol.setText(x.getTipo_usuario());
                        Inventory.lblNombre.setText(x.getNombre_empleado());
                        Inventory.lblSucursal.setText(x.getNombre_sucursal());

                        rol = x.getTipo_usuario();
                        
                        //Mensaje.manipulacionExcepciones("informacion", "Bienvenido " + x.getTipo_usuario(), "Tipo Usuario");
                        
                        if (x.getTipo_usuario().equals("Administrador")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(true);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(true);
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(true);

                            // Notificaciones
                            Inventory.btnFacturaCliente.setVisible(true);
                            Inventory.btnFacturasProveedor.setVisible(true);
                            Inventory.btnGarantiaCliente.setVisible(true);
                            Inventory.btnGarantiaProveedor.setVisible(true);
                            Inventory.btnReparaciones.setVisible(true);
                            Inventory.btnAnticipos.setVisible(true);
                            Inventory.btnActualizar.setVisible(true);

                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Jefe Sucursal")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);

                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            Inventory.menuMovimientoGarantia.setVisible(true);
                            
                            // Notificaciones
                            Inventory.btnFacturaCliente.setVisible(true);
                            Inventory.btnGarantiaCliente.setVisible(true);
                            Inventory.btnGarantiaProveedor.setVisible(true);
                            Inventory.btnReparaciones.setVisible(true);
                            Inventory.btnAnticipos.setVisible(true);
                            Inventory.btnActualizar.setVisible(true);

                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Secretaria")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(false);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false);
                            Inventory.btnAccesoVentaDeProductos.setVisible(false);
                            Inventory.btnAccesoConsultaProductos.setVisible(false);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(false);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuVentaDeProductos.setVisible(false);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(false);
                            Inventory.menuCierreDeCaja.setVisible(false);
                            Inventory.menuAnulacionVentas.setVisible(false);
                            Inventory.menuAbonoDeClientes.setVisible(false);
                            Inventory.menuAnticipo.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false);
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);

                            //Items menu catalogos
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(true);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuConsultaProductos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            Inventory.menuAjusteInventario.setVisible(false);

                            Inventory.sepMenuBaseDeDatos.setVisible(false);

                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Cajero")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(false);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(false);
                            Inventory.btnAccesoVentaDeProductos.setVisible(false);
                            Inventory.btnAccesoConsultaProductos.setVisible(false);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(false);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuVentaDeProductos.setVisible(false);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            Inventory.menuAnulacionVentas.setVisible(true);
                            Inventory.menuAbonoDeClientes.setVisible(true);
                            Inventory.menuAnticipo.setVisible(true);
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false);
                            
                            // Items del menu reportes
                            Inventory.menuComisiones.setVisible(false);
                            Inventory.menuCompras.setVisible(false);
                            Inventory.menuVentas.setVisible(true);
                            Inventory.menuInventario.setVisible(false);
                            
                            
                            //Base de datos
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            
                            //Items menu catalogos
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuConsultaProductos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(false); // Menu Usuarios
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);

                            this.dispose();

                        }
                        
                        if (x.getTipo_usuario().equals("Tecnico")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(false);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(false);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(false);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(false);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuVentaDeProductos.setVisible(false);
                            Inventory.menuProforma.setVisible(false);
                            Inventory.menuVentasActivas.setVisible(false);
                            Inventory.menuCierreDeCaja.setVisible(false);
                            Inventory.menuAnulacionVentas.setVisible(false);
                            Inventory.menuAbonoDeClientes.setVisible(false);
                            Inventory.menuAnticipo.setVisible(false);
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuMovimientoGarantia.setVisible(false);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(false);

                            //Items menu catalogos
                            Inventory.menuClientes.setVisible(false);
                            Inventory.menuProveedores.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuConsultaProductos.setVisible(true);
                            Inventory.menuUsuarios.setVisible(false); // Menu Usuarios
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            //Menu de base de datos
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(false);
                            Inventory.menuExportarCatalogoDeProductos.setVisible(false);
                            Inventory.menuImportarCatalogoDeProductos.setVisible(false);
                            Inventory.sepExportar.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeCompras.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeVentas.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeProforma.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialTraslado.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(false);
                            Inventory.sepMenuBaseDeDatos.setVisible(false);
                            
                            // Notificaciones
                            Inventory.btnReparaciones.setVisible(true);
                            Inventory.btnActualizar.setVisible(true);

                            this.dispose();

                        }
                        
                        if (x.getTipo_usuario().equals("Vendedor")) {
                            
                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(true);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            // Sub menu Compras
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            Inventory.menuRetencionProveedor.setVisible(false);
                            
                            // Sub menu Garantias
                            Inventory.menuMovimientoGarantia.setVisible(true);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(true);
                            
                            // Sub menu Inventario
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuTraslado.setVisible(true);
                            
                            // Sub menu Ventas
                            Inventory.menuVentaDeProductos.setVisible(true);
                            Inventory.menuAbonoDeClientes.setVisible(true);
                            Inventory.menuAnulacionVentas.setVisible(false);
                            Inventory.menuAnticipo.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            Inventory.menuProforma.setVisible(true);
                            //Esto se coloco solo porque los de las librerias
                            //no quieren que los usuarios vean la pantalla
                            //de ventas porque es confidencial segun ellos
                            if(PantallaVentasActivas.equals("SI")) {
                                Inventory.menuVentasActivas.setVisible(true);
                            } else {
                                Inventory.menuVentasActivas.setVisible(false);
                            }
                            Inventory.menuCierreDeCaja.setVisible(true);
                            
                            // Sub menu Taller
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            
                            //Items menu catalogos
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuMarcas.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuSeries.setVisible(true); 
                            Inventory.menuConsultaProductos.setVisible(true);
                            
                            Inventory.sepMenuCatalogoUno.setVisible(false);
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            Inventory.sepMenuCatalogoDos.setVisible(true);
                            Inventory.menuClientes.setVisible(true);
                            // Quitar los benditos proveedores para que
                            // no los vean los vendedores que lata
                            if(PantallaProveedores.equals("SI")) {
                                Inventory.menuProveedores.setVisible(true);
                            } else {
                                Inventory.menuProveedores.setVisible(false);
                            }
                            
                            //Reportes
                            Inventory.menuComisiones.setVisible(false);
                            Inventory.menuCompras.setVisible(false);
                            //Esto se coloco solo porque los de las librerias
                            //no quieren que los usuarios vean los reportes
                            //de ventas porque es confidencial segun ellos
                            if(ReportesDeVentas.equals("SI")) {
                                ver_reportes_ventas = true;
                            } else {
                                ver_reportes_ventas = false;
                            }
                            Inventory.menuVentas.setVisible(ver_reportes_ventas);
                            Inventory.menuInventario.setVisible(false);
                            Inventory.menuReportesDetalleGanancia.setVisible(false);
                            
                            //Base de datos
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuExportarCatalogoDeProductos.setVisible(false);
                            Inventory.menuImportarCatalogoDeProductos.setVisible(false);
                            Inventory.sepExportar.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialDeCompras.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeVentas.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialDeProforma.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialTraslado.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(true);
                            
                            // Notificaciones
                            Inventory.btnFacturaCliente.setVisible(true);
                            Inventory.btnGarantiaCliente.setVisible(true);
                            Inventory.btnGarantiaProveedor.setVisible(true);
                            Inventory.btnReparaciones.setVisible(true);
                            Inventory.btnAnticipos.setVisible(true);
                            Inventory.btnActualizar.setVisible(true);
                            
                            this.dispose();

                        }

                        if (x.getTipo_usuario().equals("Encargado")) {

                            // Accesos directos
                            Inventory.btnAccesoProforma.setVisible(true);
                            Inventory.btnAccesoOrdenDeServicio.setVisible(true);
                            Inventory.btnAccesoConsultaProductos.setVisible(true);
                            Inventory.btnAccesoVentaDeProductos.setVisible(true);

                            // Items del menu principal
                            Inventory.menu.setVisible(true);
                            Inventory.menuMovimiento.setVisible(true);
                            Inventory.menuCatalogo.setVisible(true);
                            Inventory.menuContabilidad.setVisible(false);
                            Inventory.menuReportes.setVisible(true);
                            Inventory.menuBaseDeDatos.setVisible(false);
                            Inventory.menuAyuda.setVisible(true);

                            // Items del menu movimientos
                            // Sub menu Compras
                            Inventory.menuCompraDeProductos.setVisible(false);
                            Inventory.menuAbonoProveedores.setVisible(false);
                            Inventory.menuTraslado.setVisible(false);
                            
                            // Sub menu Garantias
                            Inventory.menuMovimientoGarantia.setVisible(true);
                            Inventory.menuMovimientoGarantiaProveedor.setVisible(true);
                            
                            // Sub menu Inventario
                            Inventory.menuAjusteInventario.setVisible(false);
                            Inventory.menuIntercambiarSerie.setVisible(false);
                            Inventory.menuTraslado.setVisible(true);
                            
                            // Sub menu Ventas
                            Inventory.menuVentaDeProductos.setVisible(true);
                            Inventory.menuAbonoDeClientes.setVisible(true);
                            Inventory.menuAnulacionVentas.setVisible(true);
                            Inventory.menuAnticipo.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            Inventory.menuProforma.setVisible(true);
                            Inventory.menuVentasActivas.setVisible(true);
                            Inventory.menuCierreDeCaja.setVisible(true);
                            
                            // Sub menu Taller
                            Inventory.menuOrdenDeServicio.setVisible(true);
                            
                            
                            //Items menu catalogos
                            Inventory.menuCategorias.setVisible(false);
                            Inventory.menuMarcas.setVisible(false);
                            Inventory.menuProductos.setVisible(false);
                            Inventory.menuFallas.setVisible(false);
                            Inventory.menuRecargos.setVisible(false);
                            Inventory.menuSeries.setVisible(true);
                            Inventory.menuConsultaProductos.setVisible(true);
                            
                            Inventory.sepMenuCatalogoUno.setVisible(false);
                            Inventory.menuSucursales.setVisible(false);
                            Inventory.menuEmpleados.setVisible(false);
                            Inventory.menuUsuarios.setVisible(false);
                            Inventory.menuBonificaciones.setVisible(false);
                            
                            Inventory.sepMenuCatalogoDos.setVisible(true);
                            Inventory.menuClientes.setVisible(true);
                            Inventory.menuProveedores.setVisible(true);
                            
                            //Reportes
                            Inventory.menuComisiones.setVisible(false);
                            Inventory.menuCompras.setVisible(false);
                            Inventory.menuVentas.setVisible(true);
                            Inventory.menuInventario.setVisible(false);
                            Inventory.menuReportesDetalleGanancia.setVisible(false);
                            
                            //Base de datos
                            Inventory.menuBaseDeDatos.setVisible(true);
                            Inventory.menuExportarCatalogoDeProductos.setVisible(false);
                            Inventory.menuImportarCatalogoDeProductos.setVisible(false);
                            Inventory.sepExportar.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialAnticipos.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialDeCompras.setVisible(false);
                            Inventory.menuBaseDeDatosHistorialDeVentas.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialDeProforma.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialTraslado.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialOrdenes.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialGarantiaCliente.setVisible(true);
                            Inventory.menuBaseDeDatosHistorialGarantiaProveedor.setVisible(true);
                            
                            // Notificaciones
                            Inventory.btnFacturaCliente.setVisible(true);
                            Inventory.btnGarantiaCliente.setVisible(true);
                            Inventory.btnGarantiaProveedor.setVisible(true);
                            Inventory.btnReparaciones.setVisible(true);
                            Inventory.btnAnticipos.setVisible(true);
                            Inventory.btnActualizar.setVisible(true);
                            
                            this.dispose();

                        }
                        
                    }
                    
                    //Habilitar el modulo de contabilidad en el menu principal
                    //Esta opcion debe de activarse en el archivo de configuraciones
                    try {
                        if (Archivo.leer("[Conta]").equals("FALSE")) {
                            Inventory.menuContabilidad.setVisible(false);
                        } else {
                            if (rol.equals("Administrador")) {
                                Inventory.menuContabilidad.setVisible(true);
                            } else {
                                Inventory.menuContabilidad.setVisible(false);
                            }
                        }
                    } catch (IOException ex) {
                        System.out.println("Error al activar modulo contable");
                    }
                    
                    
                    //habilitar pantalla de Log
                    try {
                        if(Archivo.leer("[LOG]").equals("TRUE")) {
                            Inventory.pnlLog.setVisible(true);
                        }
                    } catch (IOException Error) {
                        Mensaje.manipulacionExcepciones("Critico", Error.toString(), "Habilitar Pantalla de LOG");
                        System.out.println("Error al activar el Log.");
                    }

                    //colocar el nombre de la terminal en la pantalla principal
                    Inventory.lblTerminal.setText(String.valueOf(lista_terminal.listIterator(0).next().getId_terminal()));
                    
                    //Colocar el fondo del usuario en la pantalla principal
                    Inventory.definirFondoUsuario();

                } else {

                    Mensaje.manipulacionExcepciones("critico", "El equiopo " + MacAdress + " no cuenta con licencia de uso.", "Comprobar Usuario");

                }

            }
        }

        txtContrasenia.setText("");
        txtUsuario.setText("");
        txtUsuario.requestFocus();
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        
        System.out.println("Presiono el boton aceptar");
        
        try {
            
            Date date = new Date();
            String key = Archivo.leer("[Key]");
            DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            
            try {
                
                System.out.println("Buscar fecha actual");
                String reloj = date.getDate() + "/" + (date.getMonth() + 1) + "/" + (date.getYear() + 1900);
                Date fecha_final = formato.parse(key);
                Date fecha_actual = formato.parse(reloj);
                
                //validar si puede entrar a la aplicacion segun la fecha
                if (fecha_actual.before(fecha_final)) {
                    if (txtUsuario.getText().equals("megabytes") && txtContrasenia.getText().equals("Derwin2012mg")) {
                        Inventory.menu.setVisible(true);
                        Inventory.lblRol.setText("DBA");
                        Inventory.lblUsuario.setText("Soporte");
                        Inventory.sepMenuBaseDeDatos.setVisible(true);
                        Inventory.menuBaseDeDatosMantenimiento.setVisible(true);
                        this.dispose();
                    } else {
                        System.out.println("Quitar accesos de menus para desarrollador");
                        Inventory.sepMenuBaseDeDatos.setVisible(false);
                        Inventory.menuBaseDeDatosMantenimiento.setVisible(false);
                        System.out.println("Comprobar usuario");
                        comprobarUsuario();
                    }
                } else {
                    Mensaje.manipulacionExcepciones("critico", "Por favor adquiera la licencia de este producto para el equipo " + MacAdress + ".", "Boton Aceptar");
                }
                
            } catch (ParseException ex) {
                Mensaje.manipulacionExcepciones("critico", "Error al formatear la fecha.", "Boton Aceptar");
            }

        } catch (IOException ex) {
            Mensaje.manipulacionExcepciones("critico", ex.getMessage(), "Boton Aceptar");
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseniaKeyPressed
        
        if (evt.getKeyCode() == 10) {
            
            System.out.println("Presiono ENTER");
            
            try {
                
                Date date = new Date();
                String key = Archivo.leer("[Key]");
                DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                
                String reloj = date.getDate() + "/" + (date.getMonth() + 1) + "/" + (date.getYear() + 1900);
                Date fecha_final = formato.parse(key);
                Date fecha_actual = formato.parse(reloj);

                //validar si puede entrar a la aplicacion segun la fecha
                if (fecha_actual.before(fecha_final)) {                    
                    if (txtUsuario.getText().equals("megabytes") && txtContrasenia.getText().equals("Derwin2012mg")) {
                        Inventory.menu.setVisible(true);
                        Inventory.lblRol.setText("DBA");
                        Inventory.lblUsuario.setText("Soporte");
                        Inventory.sepMenuBaseDeDatos.setVisible(true);
                        Inventory.menuBaseDeDatosMantenimiento.setVisible(true);
                        this.dispose();
                    } else {
                        Inventory.sepMenuBaseDeDatos.setVisible(false);
                        Inventory.menuBaseDeDatosMantenimiento.setVisible(false);
                        comprobarUsuario();
                    }
                    
                } else {
                    Mensaje.manipulacionExcepciones("critico", "Por favor adquiera la licencia de este producto para el equipo " + MacAdress + ".", "Contraseña");
                }
                
            } catch (ParseException ex) {
                Mensaje.manipulacionExcepciones("critico", ex.getMessage(), "Buscar Fecha");
            } catch (IOException ex) {
                Mensaje.manipulacionExcepciones("critico", ex.getMessage(), "Buscar KEY Producto");
            }
        }
        
    }//GEN-LAST:event_txtContraseniaKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
