/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import com.toedter.calendar.JDateChooser;
import inventory.acceso.*;
import inventory.objetos.ObjetosAbonoProveedor;
import inventory.objetos.ObjetosCompra;
import inventory.objetos.ObjetosSucursal;
import inventory.servicios.Matematicas;
import java.awt.Dimension;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author FERNANDO
 */
public class wdwMovimientoAbonoProveedor extends javax.swing.JInternalFrame {


    private ObjetosAbonoProveedor objeto = new ObjetosAbonoProveedor();
    private AccesoAbonoProveedor ctrlAbono;
    private Matematicas matematicas = new Matematicas();
    AccesoExcepciones Mensaje = new AccesoExcepciones();

    int activarEvento = 0;
    public wdwMovimientoAbonoProveedor() {
        initComponents();
        ctrlAbono = new AccesoAbonoProveedor(this,objeto);
    
    }
    
    public String ConvertirFecha(JDateChooser Calendario) {
        if ( Calendario.getDate() == null ) {
            return null;
        } else {
        return ( Calendario.getDate().getYear() + 1900 ) + "-" + ( Calendario.getDate().getMonth() + 1 ) + "-" + Calendario.getDate().getDate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDproveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdcompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtCantidadAbono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcomboTipoAbono = new javax.swing.JComboBox<>();
        txtBancoDoc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSerieDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNoDoc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFechaAbono = new com.toedter.calendar.JDateChooser();
        pnlBotones = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnGuardarAbono = new javax.swing.JButton();
        txtBusquedaNombre = new javax.swing.JTextField();
        btnBuscarNombre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarFactura = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarSerie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBuscarNumero = new javax.swing.JTextField();
        txtIdFactura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnBuscarIdFactura = new javax.swing.JButton();
        btnBuscarSerie = new javax.swing.JButton();
        pnlDetalle = new javax.swing.JPanel();
        scrollpanetable = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        pnlImpresion = new javax.swing.JPanel();
        btnReporte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Abono a Proveedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgAbonoProveedores.png"))); // NOI18N

        panelEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID Proveedor");

        txtIDproveedor.setEditable(false);
        txtIDproveedor.setBackground(new java.awt.Color(102, 102, 102));
        txtIDproveedor.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("NIT");

        txtNit.setEditable(false);
        txtNit.setBackground(new java.awt.Color(102, 102, 102));
        txtNit.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("ID Compra");

        txtIdcompra.setEditable(false);
        txtIdcompra.setBackground(new java.awt.Color(102, 102, 102));
        txtIdcompra.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Saldo");

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(102, 102, 102));
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));

        txtCantidadAbono.setBackground(new java.awt.Color(255, 255, 204));
        txtCantidadAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadAbonoKeyTyped(evt);
            }
        });

        jLabel7.setText("Abono");

        jLabel8.setText("Tipo");

        jcomboTipoAbono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Cheque", "Tarjeta", "Nota Crédito" }));
        jcomboTipoAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboTipoAbonoActionPerformed(evt);
            }
        });

        txtBancoDoc.setBackground(new java.awt.Color(255, 255, 204));
        txtBancoDoc.setEnabled(false);

        jLabel14.setText("Banco");

        txtSerieDoc.setBackground(new java.awt.Color(255, 255, 209));
        txtSerieDoc.setEnabled(false);

        jLabel10.setText("Serie");

        txtNoDoc.setBackground(new java.awt.Color(255, 255, 204));
        txtNoDoc.setEnabled(false);

        jLabel13.setText("Numero");

        jLabel15.setText("Fecha");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIDproveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantidadAbono)
                    .addComponent(txtFechaAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSaldo)
                            .addComponent(jcomboTipoAbono, 0, 139, Short.MAX_VALUE)
                            .addComponent(txtSerieDoc))
                        .addGap(18, 18, 18)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(32, 32, 32)))
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBancoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNombre))
                .addContainerGap())
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboTipoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel15)
                                .addComponent(txtSerieDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFechaAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtIdcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtBancoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setText("NIT");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonLimpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.setToolTipText("Ingrese NIT del proveedor");

        btnGuardarAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonGuardar.png"))); // NOI18N
        btnGuardarAbono.setText("Guardar");
        btnGuardarAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAbonoActionPerformed(evt);
            }
        });

        btnBuscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarNombre.setActionCommand("buscar");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        btnBuscarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarFactura.setActionCommand("buscar");
        btnBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturaActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Serie");

        jLabel11.setText("Numero");

        jLabel12.setText("ID Compra");

        btnBuscarIdFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarIdFactura.setActionCommand("buscar");
        btnBuscarIdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdFacturaActionPerformed(evt);
            }
        });

        btnBuscarSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarSerie.setActionCommand("buscar");
        btnBuscarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(txtBuscarSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(btnBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarAbono))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(btnBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarFactura)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtBuscarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(btnBuscarIdFactura)
                    .addComponent(btnBuscarSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnBuscarNombre)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar)
                        .addComponent(btnGuardarAbono))
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addContainerGap())
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedorMouseClicked(evt);
            }
        });
        scrollpanetable.setViewportView(tablaProveedor);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanetable)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanetable, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlImpresion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonImpresoraLaser.png"))); // NOI18N
        btnReporte.setActionCommand("btnReporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlImpresionLayout = new javax.swing.GroupLayout(pnlImpresion);
        pnlImpresion.setLayout(pnlImpresionLayout);
        pnlImpresionLayout.setHorizontalGroup(
            pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlImpresionLayout.setVerticalGroup(
            pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImpresionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReporte)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEncabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        this.txtIDproveedor.setText("");
        this.txtNit.setText("");
        this.txtNombre.setText("");
        this.txtSaldo.setText("");
        this.txtIdcompra.setText("");  
        txtBancoDoc.setText("");
        txtNoDoc.setText("");
        txtSerieDoc.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        /*if (!this.txtBuscar.getText().equals("")) {
            activarEvento = 1;
            ctrlAbono.buscarPersona(this.txtBuscar.getText().trim());
            ctrlAbono.buscarFacturaPendiente();
            ctrlAbono.detallarCompra();
        } else {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de NIT.", "Buscar por NIT");
        }*/
        if (txtBuscar.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el NIT del Proveedor que desea buscar.", "Bucar por Nombre");
        } else {
            AccesoCompra acceso = new AccesoCompra();
            ArrayList<ObjetosCompra> lista_datos = new ArrayList<>();
            lista_datos = acceso.buscarComprasAlCreditoPorNit(txtBuscar.getText().trim(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            Iterator iterador = lista_datos.iterator();
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Proveedor","NIT Proveedor","Proveedor","Saldo Pendiente","ID Compra","Fecha Compra","Serie","Numero"}, 0);
            for(ObjetosCompra x : lista_datos) {
                modelo.addRow(new Object[]{x.getId_proveedor(), x.getNit_proveedor(), x.getNombre_proveedor(), x.getSaldo_pendiente(), x.getId_compra(), x.getFecha_factura_compra(), x.getSerie_factura_compra(), x.getNumero_factura_compra()});
            }
            tablaProveedor.setModel(modelo);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedorMouseClicked
        this.txtIDproveedor.setText(String.valueOf(this.tablaProveedor.getValueAt(this.tablaProveedor.rowAtPoint(evt.getPoint()), 0)));;
        this.txtNit.setText(String.valueOf(this.tablaProveedor.getValueAt(this.tablaProveedor.rowAtPoint(evt.getPoint()), 1)));
        this.txtNombre.setText(String.valueOf(this.tablaProveedor.getValueAt(this.tablaProveedor.rowAtPoint(evt.getPoint()), 2)));
        double valor = Double.parseDouble(this.tablaProveedor.getValueAt(this.tablaProveedor.rowAtPoint(evt.getPoint()), 3).toString());
        double saldo = matematicas.aproxima(valor, 2);
        this.txtSaldo.setText(String.valueOf(saldo));
        this.txtIdcompra.setText(String.valueOf(this.tablaProveedor.getValueAt(this.tablaProveedor.rowAtPoint(evt.getPoint()), 4)));
    }//GEN-LAST:event_tablaProveedorMouseClicked

    private void btnGuardarAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAbonoActionPerformed

        String nit_modificado = txtNit.getText().trim();
        
        if(this.txtIDproveedor.getText().equals("")|| this.txtCantidadAbono.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresa la cantidad a abonar y selecciona una cuenta.");
        } else if(ctrlAbono.validarTipoAbono(String.valueOf(this.jcomboTipoAbono.getSelectedItem()), this.txtBancoDoc.getText(), this.txtNoDoc.getText()) == 1) {
            objeto.setIdProveedor(this.txtIDproveedor.getText());
            objeto.setNombreProv(this.txtNombre.getText());
            objeto.setTipoDoc(String.valueOf(this.jcomboTipoAbono.getSelectedItem()));
            objeto.setSaldoPendiente(Double.parseDouble(this.txtSaldo.getText()) - Double.parseDouble(this.txtCantidadAbono.getText()));
            objeto.setCantidadAbono(Double.parseDouble(this.txtCantidadAbono.getText()));
            objeto.setIdCompra(this.txtIdcompra.getText());
            objeto.setFechaAbono(ConvertirFecha(txtFechaAbono));
            objeto.setNumeroDoc(this.txtNoDoc.getText());
            objeto.setBanco(this.txtBancoDoc.getText());
            objeto.setNitProveedor(this.txtNit.getText());
            objeto.setSerieDoc(this.txtSerieDoc.getText());
            ctrlAbono.registrarAbono(objeto, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            activarEvento = 0;
       }

        AccesoCompra acceso = new AccesoCompra();
        ArrayList<ObjetosCompra> lista_datos = new ArrayList<>();
        lista_datos = acceso.buscarComprasAlCreditoPorNit(nit_modificado, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        Iterator iterador = lista_datos.iterator();
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Proveedor", "NIT Proveedor", "Proveedor", "Saldo Pendiente", "ID Compra", "Fecha Compra", "Serie", "Numero"}, 0);
        for (ObjetosCompra x : lista_datos) {
            modelo.addRow(new Object[]{x.getId_proveedor(), x.getNit_proveedor(), x.getNombre_proveedor(), x.getSaldo_pendiente(), x.getId_compra(), x.getFecha_factura_compra(), x.getSerie_factura_compra(), x.getNumero_factura_compra()});
        }
        tablaProveedor.setModel(modelo);
        
    }//GEN-LAST:event_btnGuardarAbonoActionPerformed

    private void txtCantidadAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadAbonoKeyTyped
         char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "solo se permiten números");
        }
    }//GEN-LAST:event_txtCantidadAbonoKeyTyped

    private void jcomboTipoAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboTipoAbonoActionPerformed
        String tipo = String.valueOf(this.jcomboTipoAbono.getSelectedItem());
        switch(tipo){
            case "Tarjeta":
                this.txtBancoDoc.setEnabled(true);
                this.txtNoDoc.setEnabled(true);
                this.txtSerieDoc.setEnabled(false);
                txtSerieDoc.setText("");
                break;
            case "Cheque":
                this.txtBancoDoc.setEnabled(true);
                this.txtNoDoc.setEnabled(true);
                this.txtSerieDoc.setEnabled(false);
                break;
            case "Efectivo":
                this.txtBancoDoc.setEnabled(false);
                this.txtNoDoc.setEnabled(false);
                this.txtSerieDoc.setEnabled(false);
                txtBancoDoc.setText("");
                txtNoDoc.setText("");
                txtSerieDoc.setText("");
                break;
            case "Nota Crédito":
                this.txtBancoDoc.setEnabled(false);
                this.txtNoDoc.setEnabled(true);
                this.txtSerieDoc.setEnabled(true);
                txtBancoDoc.setText("");
                break;
            default:
                break;
                
        }
    }//GEN-LAST:event_jcomboTipoAbonoActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed

        try {

            AccesoInventario acceso_inventario = new AccesoInventario();
            AccesoSucursal acceso_sucursal = new AccesoSucursal();
            ObjetosSucursal objeto_sucursal = new ObjetosSucursal();

            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptCompra.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();

            //parametros generales del encabezado
            objeto_sucursal = acceso_sucursal.buscarSucursales(1, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

            //parametros del reporte
            parametro.put("P_ID_COMPRA", Integer.parseInt(txtIdcompra.getText()));
            parametro.put("P_DIRECCION_SUCURSAL", objeto_sucursal.getDireccion_sucursal());
            parametro.put("P_NIT", objeto_sucursal.getNit_sucursal());
            parametro.put("P_NOMBRE_EMPRESA", objeto_sucursal.getNombre_sucursal());
            parametro.put("P_SUCURSAL", objeto_sucursal.getDescripcion_sucursal());
            parametro.put("P_TELEFONO", objeto_sucursal.getTelefonos_sucursal());

            //parametros facturación FEL implementarlos solo si se desea
            //obtener facturacion electronica de la venta realizada
            //parametro.put("P_SERIE_FEL", tblDetalleCompra.getValueAt(tblDetalleCompra.getSelectedRow(), 2).toString());
            //parametro.put("P_NUMERO_FEL", tblDetalleCompra.getValueAt(tblDetalleCompra.getSelectedRow(), 1).toString());
            //parametro.put("P_AUTORIZACION_FEL", tblDetalleCompra.getValueAt(tblDetalleCompra.getSelectedRow(), 3).toString());

            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso_inventario.conectar());
            JInternalFrame ventana = new JInternalFrame("Inventory 3.0");
            ventana.getContentPane().add(new JRViewer(pantalla));
            ventana.setPreferredSize(new Dimension(900, 500));
            ventana.setClosable(true);
            ventana.setMaximizable(true);
            ventana.setResizable(true);
            ventana.setVisible(true);
            ventana.pack();

            int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
            int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
            int x = (ancho - ventana.getWidth()) / 2;
            int y = (alto - ventana.getHeight() - 100) / 2;

            Inventory.pnlPrincipal.add(ventana);

            ventana.setLocation(x, y);
            ventana.setVisible(true);
            ventana.toFront();

        } catch (JRException error) {
            Mensaje.manipulacionExcepciones("critico", error.getMessage(), "Reporte de Compra");
        }

    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        if (txtBusquedaNombre.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el nombre del Proveedor que desea buscar.", "Bucar por Nombre");
        } else {
            AccesoCompra acceso = new AccesoCompra();
            ArrayList<ObjetosCompra> lista_datos = new ArrayList<>();
            lista_datos = acceso.buscarComprasAlCreditoPorNombre(txtBusquedaNombre.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            Iterator iterador = lista_datos.iterator();
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Proveedor","NIT Proveedor","Proveedor","Saldo Pendiente","ID Compra","Fecha Compra","Serie","Numero"}, 0);
            for(ObjetosCompra x : lista_datos) {
                modelo.addRow(new Object[]{x.getId_proveedor(), x.getNit_proveedor(), x.getNombre_proveedor(), x.getSaldo_pendiente(), x.getId_compra(), x.getFecha_factura_compra(), x.getSerie_factura_compra(), x.getNumero_factura_compra()});
            }
            tablaProveedor.setModel(modelo);
        }
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaActionPerformed
        if (txtBuscarNumero.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de la Factura que desea buscar.", "Bucar por Nombre");
        } else {
            AccesoCompra acceso = new AccesoCompra();
            ArrayList<ObjetosCompra> lista_datos = new ArrayList<>();
            lista_datos = acceso.buscarComprasAlCreditoPorNumeroFacturaFEL(txtBuscarNumero.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            Iterator iterador = lista_datos.iterator();
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Proveedor","NIT Proveedor","Proveedor","Saldo Pendiente","ID Compra","Fecha Compra","Serie","Numero"}, 0);
            for(ObjetosCompra x : lista_datos) {
                modelo.addRow(new Object[]{x.getId_proveedor(), x.getNit_proveedor(), x.getNombre_proveedor(), x.getSaldo_pendiente(), x.getId_compra(), x.getFecha_factura_compra(), x.getSerie_factura_compra(), x.getNumero_factura_compra()});
            }
            tablaProveedor.setModel(modelo);
        }
    }//GEN-LAST:event_btnBuscarFacturaActionPerformed

    private void btnBuscarIdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el ID de la Compra.", "Bucar por ID Compra");
        } else {
            AccesoCompra acceso = new AccesoCompra();
            ArrayList<ObjetosCompra> lista_datos = new ArrayList<>();
            lista_datos = acceso.buscarComprasPorId(txtIdFactura.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            Iterator iterador = lista_datos.iterator();
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Proveedor","NIT Proveedor","Proveedor","Saldo Pendiente","ID Compra","Fecha Compra","Serie","Numero"}, 0);
            for(ObjetosCompra x : lista_datos) {
                modelo.addRow(new Object[]{x.getId_proveedor(), x.getNit_proveedor(), x.getNombre_proveedor(), x.getSaldo_pendiente(), x.getId_compra(), x.getFecha_factura_compra(), x.getSerie_factura_compra(), x.getNumero_factura_compra()});
            }
            tablaProveedor.setModel(modelo);
        }
    }//GEN-LAST:event_btnBuscarIdFacturaActionPerformed

    private void btnBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSerieActionPerformed
        if (txtBuscarSerie.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese la serie de la Factura que desea buscar.", "Bucar por Nombre");
        } else {
            AccesoCompra acceso = new AccesoCompra();
            ArrayList<ObjetosCompra> lista_datos = new ArrayList<>();
            lista_datos = acceso.buscarComprasAlCreditoPorSerieFacturaFEL(txtBuscarSerie.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            Iterator iterador = lista_datos.iterator();
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Proveedor","NIT Proveedor","Proveedor","Saldo Pendiente","ID Compra","Fecha Compra","Serie","Numero"}, 0);
            for(ObjetosCompra x : lista_datos) {
                modelo.addRow(new Object[]{x.getId_proveedor(), x.getNit_proveedor(), x.getNombre_proveedor(), x.getSaldo_pendiente(), x.getId_compra(), x.getFecha_factura_compra(), x.getSerie_factura_compra(), x.getNumero_factura_compra()});
            }
            tablaProveedor.setModel(modelo);
        }
    }//GEN-LAST:event_btnBuscarSerieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JButton btnBuscarIdFactura;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnBuscarSerie;
    private javax.swing.JButton btnGuardarAbono;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JComboBox<String> jcomboTipoAbono;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlImpresion;
    private javax.swing.JScrollPane scrollpanetable;
    public javax.swing.JTable tablaProveedor;
    public javax.swing.JTextField txtBancoDoc;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarNumero;
    private javax.swing.JTextField txtBuscarSerie;
    private javax.swing.JTextField txtBusquedaNombre;
    public javax.swing.JTextField txtCantidadAbono;
    public static com.toedter.calendar.JDateChooser txtFechaAbono;
    public javax.swing.JTextField txtIDproveedor;
    private javax.swing.JTextField txtIdFactura;
    public javax.swing.JTextField txtIdcompra;
    public javax.swing.JTextField txtNit;
    public javax.swing.JTextField txtNoDoc;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtSaldo;
    public javax.swing.JTextField txtSerieDoc;
    // End of variables declaration//GEN-END:variables
}
