/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoExcepciones;
import inventory.acceso.AccesoProducto;
import inventory.acceso.AccesoUsuario;
import inventory.objetos.ObjetosProducto;
import inventory.servicios.Matematicas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DSANTACRUZ
 */
public class wdwMovimientoAutorizacionVenta extends javax.swing.JInternalFrame {

    private DefaultTableModel detalle_nuevo = new DefaultTableModel();
    private AccesoExcepciones mensaje = new AccesoExcepciones();
    private Matematicas matematica = new Matematicas();
    
    /**
     * Creates new form wdwMovimientoAutorizacionVenta
     */
    public wdwMovimientoAutorizacionVenta(DefaultTableModel detalle) {
        initComponents();
        detalle_nuevo = detalle;
    }
    
    public void totalFactura() {

        double total_factura = 0;
        
        for (int c = 0; c < detalle_nuevo.getRowCount(); c++) {
            try {
                total_factura = total_factura + Float.parseFloat(detalle_nuevo.getValueAt(c, 8).toString());
            } catch (Exception error) {
                total_factura = total_factura + 0;
            }
        }
        
        double iva = matematica.aproxima(total_factura * 0.12, 2);
        double total = matematica.redondear(total_factura);
        
        System.out.println("Total: " + total);
        System.out.println("IVA: " + iva);
        
        wdwMovimientoVentaDeProductosNueva.txtTotalFactura.setText(String.valueOf(total));
        wdwMovimientoVentaDeProductosNueva.txtIva.setText(String.valueOf(iva));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        btnAutorizar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        txtMinimo = new javax.swing.JTextField();
        txtNormal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Autorizacion");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonAutorizar.png"))); // NOI18N

        pnlUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setText("Usuario");

        lblClave.setText("Clave");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblClave))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtContrasenia))
                .addContainerGap())
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAutorizar.setText("Autorizar");
        btnAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarActionPerformed(evt);
            }
        });

        pnlDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID Producto");

        txtIdProducto.setBackground(new java.awt.Color(102, 102, 102));
        txtIdProducto.setEditable(false);
        txtIdProducto.setForeground(new java.awt.Color(255, 255, 255));

        txtCantidad.setToolTipText("");

        jLabel3.setText("Cantiad");

        jLabel2.setText("Precio");

        txtDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        txtDescripcion.setEditable(false);
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Descripicion");

        txtPrecioCompra.setBackground(new java.awt.Color(0, 102, 153));
        txtPrecioCompra.setEditable(false);
        txtPrecioCompra.setForeground(new java.awt.Color(0, 102, 153));

        txtMinimo.setBackground(new java.awt.Color(0, 102, 153));
        txtMinimo.setEditable(false);
        txtMinimo.setForeground(new java.awt.Color(0, 102, 153));

        txtNormal.setBackground(new java.awt.Color(0, 102, 153));
        txtNormal.setEditable(false);
        txtNormal.setForeground(new java.awt.Color(0, 102, 153));

        jLabel5.setText("Datos");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdProducto))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNormal, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(txtPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescripcion))))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAutorizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAutorizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarActionPerformed
        
        //Consultar los datos del producto
        AccesoProducto acceso_producto = new AccesoProducto();
        AccesoUsuario acceso_usuario = new AccesoUsuario();
        ObjetosProducto producto = new ObjetosProducto();
        
        String tipo = "";
        
        try { 
            producto = acceso_producto.buscarInformacionProducto(txtIdProducto.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        } catch (Exception Error) {
            mensaje.manipulacionExcepciones("critico", "Ocurrrio un error al buscar informacion del Producto.", "Buscar Producto");
        }
        
        try { 
            tipo = acceso_usuario.retornaTipoUsuario(txtUsuario.getText(), txtContrasenia.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        } catch (Exception Error) {
            mensaje.manipulacionExcepciones("critico", "Ocurrrio un error al buscar informacion del Producto.", "Buscar Producto");
        }
        
        if(tipo.equals("Administrador")) {
            
            Float cantidad = Float.parseFloat(txtCantidad.getText());
            double precio = Double.parseDouble(txtPrecio.getText());
            double subtotal = cantidad * precio;
            
            Object[] datos = new Object[12];
            try { datos[0] = detalle_nuevo.getRowCount() + 1; } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Fila Seleccionada \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[1] = txtIdProducto.getText(); } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "ID Producto \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[2] = txtDescripcion.getText(); } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Descripcion \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[3] = cantidad; } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Cantidad Venta \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[4] = Float.parseFloat(txtPrecioCompra.getText()); } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Precio Compra \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[5] = matematica.aproxima(precio, 2); } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Precio Descuento \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[6] = Float.parseFloat(txtMinimo.getText()); } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Precio Minimo \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[7] = Float.parseFloat(txtNormal.getText()); } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Precio Normal \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[8] = subtotal; } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Total \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[9] = "S/C"; } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Comentario \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[10] = 0.0; } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Arancel \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            try { datos[11] = "NO"; } catch (Exception Error) { mensaje.manipulacionExcepciones("critico", "Guardado \nError: " + Error.getMessage(), "Dato No. " + detalle_nuevo.getRowCount() + 1); }
            
            try {
                detalle_nuevo.addRow(datos);
                wdwMovimientoVentaDeProductosNueva.tblDetalleFactura.setModel(detalle_nuevo); 
            } catch (Exception Error) {
                System.out.println("Error: " + Error.toString());
            }

            totalFactura();
            this.dispose();

            
        } else {
            mensaje.manipulacionExcepciones("critico", "Usted no puede autorizar precios.", "Autoriza Precio");
            txtUsuario.setText("");
            txtContrasenia.setText("");
        }
        
        
        
    }//GEN-LAST:event_btnAutorizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlUsuario;
    public static javax.swing.JTextField txtCantidad;
    private javax.swing.JPasswordField txtContrasenia;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtIdProducto;
    public static javax.swing.JTextField txtMinimo;
    public static javax.swing.JTextField txtNormal;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JTextField txtPrecioCompra;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
