/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.*;
import inventory.objetos.ObjetosFalla;
import inventory.objetos.ObjetosGarantiaCliente;
import inventory.objetos.ObjetosSucursal;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author FERNANDO
 */
public class wdwMovimientoGarantiaCliente extends javax.swing.JInternalFrame {

    private ObjetosGarantiaCliente objeto_garantia = new ObjetosGarantiaCliente();
    private AccesoGarantia ctrl_garantia = new AccesoGarantia();
    private AccesoDetalleSerie detalle_serie = new AccesoDetalleSerie();
    private AccesoExcepciones mensaje = new AccesoExcepciones();
    private int opcion = 0;
    AccesoArchivo archivo = new AccesoArchivo();

    public wdwMovimientoGarantiaCliente() {
        initComponents();
        obtenerFallas();
        this.txtFechaReg.setText(this.obtenerFecha());
    }
    
     private void obtenerFallas() {
        AccesoFalla acceso_falla = new AccesoFalla();
        Iterator iterador_fallas = acceso_falla.listarFallas(Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText()).iterator();
        while(iterador_fallas.hasNext()) {
            ObjetosFalla falla = (ObjetosFalla) iterador_fallas.next();
            cbxFallas.addItem(falla.getNombre_falla());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalleProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        cbxFallas = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcAcciones = new javax.swing.JComboBox<String>();
        jLabel23 = new javax.swing.JLabel();
        txtIdSerie = new javax.swing.JTextField();
        txtFechaReg = new javax.swing.JTextField();
        txtIdRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnFactura1 = new javax.swing.JButton();
        panelBuscar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBuscarNuevoproducto = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarNuevo = new javax.swing.JButton();
        tvDescripcion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tvMarca = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tvIdSerie = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tvIdFactura = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tvIdProducto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tvSerieNuevoProducto = new javax.swing.JTextField();
        txtComentario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtGarantiaCliente = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Garantia Cliente");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgMovimientoGarantiaCliente.png"))); // NOI18N

        panelDetalleProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SERIE RECIBIDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Marca");

        txtMarca.setBackground(new java.awt.Color(102, 102, 102));
        txtMarca.setEditable(false);
        txtMarca.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("NIT");

        txtNit.setBackground(new java.awt.Color(102, 102, 102));
        txtNit.setEditable(false);
        txtNit.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Descripción");

        txtDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        txtDescripcion.setEditable(false);
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Observaciones");

        txtObservaciones.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setText("Falla");

        jLabel8.setText("Fecha Actual");

        jLabel9.setText("Cliente");

        txtCliente.setBackground(new java.awt.Color(102, 102, 102));
        txtCliente.setEditable(false);
        txtCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("ID Factura");

        txtIdFactura.setBackground(new java.awt.Color(102, 102, 102));
        txtIdFactura.setEditable(false);
        txtIdFactura.setForeground(new java.awt.Color(255, 255, 255));

        txtIdProducto.setBackground(new java.awt.Color(102, 102, 102));
        txtIdProducto.setEditable(false);
        txtIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        jLabel11.setText("ID producto");

        txtDias.setBackground(new java.awt.Color(102, 102, 102));
        txtDias.setEditable(false);
        txtDias.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Dias Pendientes");

        txtFechaFin.setBackground(new java.awt.Color(102, 102, 102));
        txtFechaFin.setEditable(false);
        txtFechaFin.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Fecha Garantia");

        jLabel15.setText("Resolución");

        jcAcciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija una opción", "Cambiar Producto", "Devolución de Efectivo" }));
        jcAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAccionesActionPerformed(evt);
            }
        });

        jLabel23.setText("ID serie");

        txtIdSerie.setBackground(new java.awt.Color(102, 102, 102));
        txtIdSerie.setEditable(false);
        txtIdSerie.setForeground(new java.awt.Color(255, 255, 255));

        txtFechaReg.setBackground(new java.awt.Color(102, 102, 102));
        txtFechaReg.setEditable(false);
        txtFechaReg.setForeground(new java.awt.Color(255, 255, 255));

        txtIdRegistro.setBackground(new java.awt.Color(102, 102, 102));
        txtIdRegistro.setEditable(false);
        txtIdRegistro.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("ID Garantía Cliente");

        txtBuscar.setToolTipText("Ingrese Serie del producto");

        lblBuscar.setText("Numero de Serie");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnFactura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonImpresoraLaser.png"))); // NOI18N
        btnFactura1.setToolTipText("Imprimir Factura");
        btnFactura1.setActionCommand("imprimirEnvio");
        btnFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactura1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetalleProductoLayout = new javax.swing.GroupLayout(panelDetalleProducto);
        panelDetalleProducto.setLayout(panelDetalleProductoLayout);
        panelDetalleProductoLayout.setHorizontalGroup(
            panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                        .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addGap(24, 24, 24)
                        .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion)
                            .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(txtFechaFin))
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                                        .addComponent(txtIdFactura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFactura1))
                                    .addComponent(txtFechaReg))
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtDias)))
                            .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNit)
                                    .addComponent(jcAcciones, 0, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCliente)
                                    .addComponent(cbxFallas, 0, 498, Short.MAX_VALUE)))
                            .addComponent(txtObservaciones))))
                .addContainerGap())
        );
        panelDetalleProductoLayout.setVerticalGroup(
            panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(panelDetalleProductoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBuscar)
                                .addComponent(jLabel23)
                                .addComponent(txtIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel10)
                        .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFactura1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel7)
                    .addComponent(cbxFallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonLimpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonImpresoraLaser.png"))); // NOI18N
        btnFactura.setToolTipText("Imprimir Factura");
        btnFactura.setActionCommand("imprimirEnvio");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addComponent(btnFactura)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SERIE A ENTREGAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblBuscarNuevoproducto.setText("Numero de Serie");

        txtBuscarProducto.setToolTipText("Ingrese Serie del producto");
        txtBuscarProducto.setEnabled(false);

        btnBuscarNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarNuevo.setActionCommand("buscar");
        btnBuscarNuevo.setEnabled(false);
        btnBuscarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNuevoActionPerformed(evt);
            }
        });

        tvDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        tvDescripcion.setEditable(false);
        tvDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setText("Descripción");

        tvMarca.setBackground(new java.awt.Color(102, 102, 102));
        tvMarca.setEditable(false);
        tvMarca.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Marca");

        jLabel24.setText("ID Serie");

        tvIdSerie.setBackground(new java.awt.Color(102, 102, 102));
        tvIdSerie.setEditable(false);
        tvIdSerie.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("ID factura");

        tvIdFactura.setBackground(new java.awt.Color(102, 102, 102));
        tvIdFactura.setEditable(false);
        tvIdFactura.setForeground(new java.awt.Color(255, 255, 255));
        tvIdFactura.setEnabled(false);

        jLabel27.setText("ID producto");

        tvIdProducto.setBackground(new java.awt.Color(102, 102, 102));
        tvIdProducto.setEditable(false);
        tvIdProducto.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("Numero Serie");

        tvSerieNuevoProducto.setBackground(new java.awt.Color(102, 102, 102));
        tvSerieNuevoProducto.setEditable(false);
        tvSerieNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));

        txtComentario.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setText("Comentario");

        jLabel1.setText("Garantía");

        txtGarantiaCliente.setBackground(new java.awt.Color(102, 102, 102));
        txtGarantiaCliente.setEditable(false);
        txtGarantiaCliente.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarNuevoproducto)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel20)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tvMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(tvIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tvDescripcion))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(tvIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel19)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvSerieNuevoProducto)
                            .addComponent(tvIdProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtGarantiaCliente)))
                    .addComponent(txtComentario))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarNuevo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBuscarNuevoproducto)
                        .addComponent(jLabel24)
                        .addComponent(tvIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(tvSerieNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tvDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel1))
                    .addComponent(txtGarantiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(tvIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(tvIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetalleProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        ArrayList<ObjetosFalla> lista = new ArrayList();
        ArrayList<ObjetosGarantiaCliente> data = new ArrayList();
        this.txtFechaReg.setText(this.obtenerFecha());

        try {
            data = ctrl_garantia.buscarSerie(this.txtBuscar.getText().trim().toUpperCase().replaceAll("'", "´"), "'Vendido','Servicio'", Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            if (!data.isEmpty()) {
                for (ObjetosGarantiaCliente listaDatos : data) {
                    this.txtDescripcion.setText(listaDatos.getDescripcion());
                    this.txtMarca.setText(listaDatos.getMarca());
                    this.txtIdFactura.setText(String.valueOf(listaDatos.getIdFactura()));
                    this.txtIdProducto.setText(listaDatos.getIdProducto());
                    this.txtNit.setText(listaDatos.getNit());
                    this.txtDias.setText(String.valueOf(listaDatos.getTiempoGarantia()));
                    objeto_garantia.setSerieproducto(listaDatos.getSerieproducto());
                    this.txtCliente.setText(listaDatos.getCliente());
                    this.txtIdSerie.setText(String.valueOf(listaDatos.getIdSerie()));
                    this.txtFechaFin.setText(listaDatos.getFechaFin());
                    
                }
                data.clear();
                try {
                    lista = ctrl_garantia.listarFallas("", ""); //listarFallas(Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                    this.cbxFallas.removeAllItems();
                    for (ObjetosFalla fallas : lista) {
                        this.cbxFallas.addItem(fallas.getNombre_falla());
                    }
                    lista.clear();
                } catch (Exception e) {
                    mensaje.manipulacionExcepciones("critico", "Error " + e, "Error al buscar.");
                }
            } else {
                this.limpiarCasillas();
                mensaje.manipulacionExcepciones("informacion", "No hay resultados.", "Sin registros");
            }
        } catch (Exception e) {
            this.limpiarCasillas();
            mensaje.manipulacionExcepciones("critico", "Error " + e.getMessage(), "Error al buscar");
        }
       

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (!txtDias.getText().equals("Sin garantia") && !txtGarantiaCliente.getText().equals("S/G")) {
            
            if (this.txtIdFactura.getText().equals("") && this.txtIdProducto.getText().equals("")) {
                
                mensaje.manipulacionExcepciones("critico", "Revise la información del formulario, hay datos vacios.", "Error al guardar");
            
            } else if (this.opcion == 0 && this.tvIdProducto.getText().isEmpty()) {

                objeto_garantia.setNit(this.txtNit.getText());
                objeto_garantia.setDescripcion(this.txtDescripcion.getText());
                objeto_garantia.setFechaGuardar(this.obtenerFecha());
                objeto_garantia.setFalla(this.cbxFallas.getSelectedItem().toString());
                objeto_garantia.setMarca(this.txtMarca.getText());
                objeto_garantia.setObservaciones(this.txtObservaciones.getText().toUpperCase());
                objeto_garantia.setCliente(this.txtCliente.getText());
                objeto_garantia.setIdProducto(this.txtIdProducto.getText());
                objeto_garantia.setTiempoGarantia(this.txtDias.getText());
                objeto_garantia.setIdFactura(this.txtIdFactura.getText());
                objeto_garantia.setCliente(this.txtCliente.getText());
                objeto_garantia.setSolucion(this.jcAcciones.getSelectedItem().toString());
                objeto_garantia.setFechaGuardar(this.txtFechaReg.getText());

                //Quitar el valor nulo de todos los campos 
                objeto_garantia.setComentarioEntregar(this.txtComentario.getText().isEmpty() ? " " : this.txtComentario.getText().toUpperCase());
                objeto_garantia.setMarcaEntregar(this.tvMarca.getText().isEmpty() ? " " : this.tvMarca.getText());
                objeto_garantia.setIdSerieEntregar(this.tvIdSerie.getText().isEmpty() ? 0 : Integer.parseInt(this.tvIdSerie.getText()));
                objeto_garantia.setIdProductoEntregar(this.tvIdProducto.getText().isEmpty() ? " " : this.tvIdProducto.getText());
                objeto_garantia.setProductoEntregar(this.tvDescripcion.getText().isEmpty() ? " " : this.tvDescripcion.getText());
                objeto_garantia.setIdFacturaEntregar(this.tvIdFactura.getText().isEmpty() ? " " : this.tvIdFactura.getText());
                objeto_garantia.setSerieEntregada(this.tvSerieNuevoProducto.getText().isEmpty() ? " " : this.tvSerieNuevoProducto.getText());

                try {

                    if (txtIdRegistro.getText().isEmpty()) {

                        int idR = ctrl_garantia.insertarReclamo(objeto_garantia, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

                        if (idR > 0) {
                            this.txtIdRegistro.setText(String.valueOf(idR));
                            detalle_serie.actualizarEstadoDetalleSerieEntregada(this.txtIdSerie.getText(), "Garantia Cliente", "Garantia Cliente", Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                            mensaje.manipulacionExcepciones("informacion", ctrl_garantia.actualizarSerieRecibidaID("Garantia Cliente", this.txtIdSerie.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText()), "Actualizar serie recibida");
                        }

                    } else {
                        
                        mensaje.manipulacionExcepciones("critico", "Este registro ya fue guardado.", "Error al guardar");
                    
                    }


                } catch (Exception e) {
                    mensaje.manipulacionExcepciones("critico", "Error al registrar solicitud", "Error al guardar");
                }

            } else if (this.opcion == 1 && !this.tvIdProducto.getText().isEmpty()) {

                objeto_garantia.setFechaGuardar(this.txtFechaReg.getText());
                objeto_garantia.setSerieEntregada(this.tvSerieNuevoProducto.getText());
                objeto_garantia.setNuevoIdFactura(this.tvIdFactura.getText());
                objeto_garantia.setNit(this.txtNit.getText());
                objeto_garantia.setDescripcion(this.txtDescripcion.getText());
                objeto_garantia.setFechaGuardar(this.obtenerFecha());
                objeto_garantia.setFalla(this.cbxFallas.getSelectedItem().toString());
                objeto_garantia.setMarca(this.txtMarca.getText());
                objeto_garantia.setObservaciones(this.txtObservaciones.getText().toUpperCase());
                objeto_garantia.setCliente(this.txtCliente.getText());
                objeto_garantia.setIdProducto(this.txtIdProducto.getText());
                objeto_garantia.setTiempoGarantia(this.txtDias.getText());
                objeto_garantia.setIdFactura(this.txtIdFactura.getText());
                objeto_garantia.setCliente(this.txtCliente.getText());
                objeto_garantia.setSolucion(this.jcAcciones.getSelectedItem().toString());

                objeto_garantia.setComentarioEntregar(this.txtComentario.getText().isEmpty() ? " " : this.txtComentario.getText().toUpperCase());
                objeto_garantia.setMarcaEntregar(this.tvMarca.getText().isEmpty() ? " " : this.tvMarca.getText());
                objeto_garantia.setIdSerieEntregar(this.tvIdSerie.getText().isEmpty() ? 0 : Integer.parseInt(this.tvIdSerie.getText()));
                objeto_garantia.setIdProductoEntregar(this.tvIdProducto.getText().isEmpty() ? " " : this.tvIdProducto.getText());
                objeto_garantia.setProductoEntregar(this.tvDescripcion.getText().isEmpty() ? " " : this.tvDescripcion.getText());
                objeto_garantia.setIdFacturaEntregar(this.tvIdFactura.getText().isEmpty() ? " " : this.tvIdFactura.getText());
                objeto_garantia.setSerieEntregada(this.tvSerieNuevoProducto.getText().isEmpty() ? " " : this.tvSerieNuevoProducto.getText());

                try {

                    if (txtIdRegistro.getText().isEmpty()) {

                        int idR = ctrl_garantia.insertarReclamo(objeto_garantia, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

                        if (idR > 0) {
                            
                            this.txtIdRegistro.setText(String.valueOf(idR));
                            
                            String mensaje_recibido = ctrl_garantia.actualizarSerieRecibidaID("Garantia Cliente", this.txtIdSerie.getText(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                            String mensaje_entregada = "";
                            
                            try {
                                if(mensaje_recibido.equals("Operacion realizada con exito.")) {
                                    mensaje_entregada = ctrl_garantia.actualizarSerieEntregada("Vendido", this.tvIdSerie.getText(), this.txtFechaFin.getText(), Integer.parseInt(this.txtIdFactura.getText()), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                                }
                            } catch (Exception e) {
                                mensaje.manipulacionExcepciones("critico", "Error actualizar serie entregada", "Error al guardar");
                            }
                            
                            if(mensaje_entregada.equals("Operacion realizada con exito.")) {
                               detalle_serie.actualizarEstadoDetalleSerieEntregada(this.tvIdSerie.getText(), "Vendido", "Garantia Cliente", Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                            } else {
                                mensaje.manipulacionExcepciones("error", "No se pudo modificar el estado de la Serie.", "Modificar estado Serie");
                            }
                            
                        }

                    } else {
                        mensaje.manipulacionExcepciones("critico", "Este registro ya fue guardado.", "Error al guardar");
                    }

                } catch (Exception e) {
                    mensaje.manipulacionExcepciones("critico", "Error al registrar solicitud.", "Error al guardar");
                }

            }
            
        } else {
            mensaje.manipulacionExcepciones("critico", "Revise los Productos ya que no tienen configurada su garantía.", "Revisar Garantía");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCasillas();
        this.limpiarNuevaCasillas();
        this.txtIdRegistro.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void btnBuscarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNuevoActionPerformed

        ArrayList<ObjetosGarantiaCliente> detalleNuevoProducto = new ArrayList();

        try {
            detalleNuevoProducto = ctrl_garantia.buscarSerie(this.txtBuscarProducto.getText().trim().toUpperCase().replaceAll("'", "´"), "'En Inventario'", Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            if (!detalleNuevoProducto.isEmpty()) {
                for (ObjetosGarantiaCliente listado : detalleNuevoProducto) {
                    if (listado.getEstadoRegistro().equals("Vendido")) {
                        mensaje.manipulacionExcepciones("critico", "Este número de serie ya se encuentra vendido",
                                "Serie fuera de inventario");
                    } else{
                    this.tvDescripcion.setText(listado.getDescripcion());
                   // this.tvDias.setText(String.valueOf(listado.getTiempoGarantia()));
                    this.tvIdProducto.setText(listado.getIdProducto());
                    this.tvMarca.setText(listado.getMarca());
                    this.tvIdFactura.setText(listado.getIdFactura());
                    this.tvSerieNuevoProducto.setText(listado.getSerieproducto());
                    this.tvIdSerie.setText(String.valueOf(listado.getIdSerie()));
                    this.txtGarantiaCliente.setText(listado.getFechaFin());
                    opcion = 1;
                    }
                }
                detalleNuevoProducto.clear();
                this.btnGuardar.setEnabled(true);
               
            } else {
                mensaje.manipulacionExcepciones("informacion", "No hay resultados", "Sin registros");
            }
        } catch (Exception e) {
            this.limpiarCasillas();
            mensaje.manipulacionExcepciones("critico", "Error " + e.getMessage(), "Error al buscar");
        }
    }//GEN-LAST:event_btnBuscarNuevoActionPerformed

    private void jcAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAccionesActionPerformed
        if (this.jcAcciones.getSelectedItem().toString().equals("Cambiar Producto")) {
            this.btnGuardar.setEnabled(false);
            this.txtBuscarProducto.setEnabled(true);
            this.btnBuscarNuevo.setEnabled(true);
        }else{
            this.btnGuardar.setEnabled(true);
            this.txtBuscarProducto.setEnabled(false);
            this.btnBuscarNuevo.setEnabled(false);
            this.limpiarNuevaCasillas();
            opcion = 0;
        }
    }//GEN-LAST:event_jcAccionesActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
      
        //ejecución del repote seleccionado
        try{
            
            AccesoInventario acceso_inventario = new AccesoInventario();
            AccesoSucursal acceso_sucursal = new AccesoSucursal();
            ObjetosSucursal objeto_sucursal = new ObjetosSucursal();
            
            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptGarantiaCliente.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();
            
            //parametros generales del encabezado
            objeto_sucursal = acceso_sucursal.buscarSucursales(1, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            
            //parametros del reporte
            parametro.put("P_DIRECCION_SUCURSAL", objeto_sucursal.getDireccion_sucursal());
            parametro.put("P_NIT", objeto_sucursal.getNit_sucursal());
            parametro.put("P_NOMBRE_EMPRESA", objeto_sucursal.getNombre_sucursal());
            parametro.put("P_SUCURSAL", objeto_sucursal.getDescripcion_sucursal());
            parametro.put("P_TELEFONO", objeto_sucursal.getTelefonos_sucursal());
            
            //parametro de busqueda
            parametro.put("P_ID_GARANTIA", Integer.parseInt(txtIdRegistro.getText().trim()));
            
            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso_inventario.conectar());
            JInternalFrame ventana = new JInternalFrame("Inventory 3.0");
            ventana.getContentPane().add(new JRViewer(pantalla));
            ventana.setPreferredSize(new Dimension(900, 500));
            ventana.setClosable(true);
            ventana.setMaximizable(true);
            ventana.setResizable(true);
            ventana.setVisible(true);
            ventana.pack();
            
            int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
            int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
            int x  = (ancho  - ventana.getWidth() ) / 2;
            int y  = ( alto - ventana.getHeight() - 100 ) / 2;
            
            Inventory.pnlPrincipal.add(ventana);
            
            ventana.setLocation(x, y);
            ventana.setVisible(true);
            ventana.toFront();
            
        } catch (JRException error) {
            mensaje.manipulacionExcepciones("critico", error.getMessage(), "Reporte de Garantia Cliente");
        }
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactura1ActionPerformed
        
        String regimen_empresa = "";
        
        //El mensaje del regimen de la factura se toma del archivo de texto
        try {
            regimen_empresa = archivo.leer("[Regimen]");
        } catch (IOException ex) {
            regimen_empresa = "";
        }
        
        
        try {

            AccesoInventario acceso_inventario = new AccesoInventario();
            AccesoSucursal acceso_sucursal = new AccesoSucursal();
            ObjetosSucursal objeto_sucursal = new ObjetosSucursal();

            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptComprobanteCarta.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();

            //parametros generales del encabezado
            objeto_sucursal = acceso_sucursal.buscarSucursales(1, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());

            //parametros del reporte
            parametro.put("P_SERIE_FACTURA", "");
            parametro.put("P_NUMERO_FACTURA", "");
            parametro.put("P_ID_FACTURA", Integer.parseInt(txtIdFactura.getText()));
            parametro.put("P_DIRECCION_SUCURSAL", objeto_sucursal.getDireccion_sucursal());
            parametro.put("P_NIT", objeto_sucursal.getNit_sucursal());
            parametro.put("P_NOMBRE_EMPRESA", objeto_sucursal.getNombre_sucursal());
            parametro.put("P_SUCURSAL", objeto_sucursal.getDescripcion_sucursal());
            parametro.put("P_TELEFONO", objeto_sucursal.getTelefonos_sucursal());

            //parametros configuracion sistema
            parametro.put("P_REGIMEN_EMPRESA", regimen_empresa);

            //parametro para la impresión de vales
            parametro.put("P_RECIBIDO", "");

            //parametros facturación FEL implementarlos solo si se desea
            //obtener facturacion electronica de la venta realizada
            parametro.put("P_SERIE_FEL", "");
            parametro.put("P_NUMERO_FEL", "");
            parametro.put("P_AUTORIZACION_FEL", "");

            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso_inventario.conectar());
            JInternalFrame ventana = new JInternalFrame("Inventory 3.0");
            ventana.getContentPane().add(new net.sf.jasperreports.view.JRViewer(pantalla));
            ventana.setPreferredSize(new Dimension(900, 500));
            ventana.setClosable(true);
            ventana.setMaximizable(true);
            ventana.setResizable(true);
            ventana.setVisible(true);
            ventana.pack();

            int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
            int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
            int x = (ancho - ventana.getWidth()) / 2;
            int y = (alto - ventana.getHeight() - 100) / 2;

            Inventory.pnlPrincipal.add(ventana);

            ventana.setLocation(x, y);
            ventana.setVisible(true);
            ventana.toFront();

        } catch (JRException error) {
            mensaje.manipulacionExcepciones("critico", error.getMessage(), "Recporte de Consulta Factura");
        }
        
    }//GEN-LAST:event_btnFactura1ActionPerformed

     private String obtenerFecha() {
        try {
            Date date = new Date();
            String fecha = new SimpleDateFormat("YYYY-MM-dd").format(date);
            return String.valueOf(fecha);
        } catch (NullPointerException ex) {
            return null;
        }
    }
     
     private String fechaChooser() {
        try {
            Date date = new Date();
            String fecha = new SimpleDateFormat("YYYY-MM-dd").format(date);
            return String.valueOf(fecha);
        } catch (NullPointerException ex) {
            return null;
        }
    }
     
    private void limpiarCasillas() {

        this.btnGuardar.setEnabled(false);
        this.txtDescripcion.setText("");
        this.txtMarca.setText("");
        this.txtIdFactura.setText("");
        this.txtIdProducto.setText("");
        this.txtNit.setText("");
        this.txtDias.setText("");
        this.txtCliente.setText("");
        this.txtBuscar.setText("");
        this.txtFechaFin.setText("");
        this.txtFechaReg.setText("");
        this.txtIdSerie.setText("");
    }
    
    private void limpiarNuevaCasillas(){
        this.tvDescripcion.setText("");
        this.txtBuscarProducto.setText("");
        this.tvIdProducto.setText("");
        this.tvMarca.setText("");
        this.tvSerieNuevoProducto.setText("");
        this.tvIdFactura.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarNuevo;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnFactura1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbxFallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcAcciones;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblBuscarNuevoproducto;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelDetalleProducto;
    private javax.swing.JTextField tvDescripcion;
    private javax.swing.JTextField tvIdFactura;
    private javax.swing.JTextField tvIdProducto;
    private javax.swing.JTextField tvIdSerie;
    private javax.swing.JTextField tvMarca;
    private javax.swing.JTextField tvSerieNuevoProducto;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaReg;
    private javax.swing.JTextField txtGarantiaCliente;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIdRegistro;
    private javax.swing.JTextField txtIdSerie;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
