/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoExcepciones;
import inventory.acceso.AccesoInventario;
import inventory.acceso.AccesoRetencion;
import inventory.acceso.AccesoSucursal;
import inventory.objetos.ObjetosRetencion;
import inventory.objetos.ObjetosSucursal;
import java.awt.Dimension;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Derwin Santa Cruz
 */
public class wdwMovimientoRetencionProveedor extends javax.swing.JInternalFrame {

    AccesoExcepciones mensaje = new AccesoExcepciones();
    ObjetosRetencion objetosRetencion = new ObjetosRetencion();
    AccesoRetencion retencion = new AccesoRetencion();
    String Log = "";
    
    /**
     * Creates new form wdwMovimientoRetencionProveedor
     */
    public wdwMovimientoRetencionProveedor() {
        initComponents();
    }
    
    private Date ConvertirDate(String valor) {
        Date fecha = null;
        try {
            if (valor == null || valor.equals("")) {
                fecha = null;
            } else {
                fecha = new SimpleDateFormat("yyyy-MM-dd").parse(valor);
            }
        } catch (Exception Error) {
            mensaje.manipulacionExcepciones("critico", "Error al convertir fecha. \n" + Error.getMessage(), "Convertir Fecha");
        }
        return fecha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdRetencion = new javax.swing.JTextField();
        txtFechaEmsion = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaPago = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdCompra = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGuia = new javax.swing.JTextField();
        txtFechaEnvio = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txtDatos = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        txtBuscarNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarNIT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBuscarNIT = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnBuscarNumero = new javax.swing.JButton();
        txtBuscarIdCompra = new javax.swing.JTextField();
        btnBuscarIdCompra = new javax.swing.JButton();
        panelImpresion = new javax.swing.JPanel();
        btnImprimirRetencion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Retención Proveedor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imbMovimientoRetencionProveedor.png"))); // NOI18N

        panelEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID Retención ");

        txtIdRetencion.setEditable(false);
        txtIdRetencion.setBackground(new java.awt.Color(102, 102, 102));
        txtIdRetencion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Fecha Emisión");

        jLabel3.setText("Número");

        txtNumero.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Monto");

        txtMonto.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("NIT");

        jLabel6.setText("ID Compra");

        jLabel7.setText("Fecha Pago");

        jLabel8.setText("Datos del pago");

        txtIdCompra.setBackground(new java.awt.Color(255, 255, 204));

        txtNit.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("No. Guia");

        txtGuia.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setText("Fecha Envio");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtIdRetencion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaEmsion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtNumero)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDatos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdRetencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFechaEmsion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Número");

        jLabel11.setText("NIT");

        btnBuscarNIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNITActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Compra");

        btnBuscarNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNumeroActionPerformed(evt);
            }
        });

        btnBuscarIdCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonBuscar.png"))); // NOI18N
        btnBuscarIdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarNumero)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarIdCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarIdCompra)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarNIT)
                .addGap(93, 93, 93))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarNIT)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12)
                        .addComponent(txtBuscarIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtBuscarNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarNumero)
                    .addComponent(btnBuscarIdCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImpresion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnImprimirRetencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonImpresoraLaser.png"))); // NOI18N
        btnImprimirRetencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRetencionActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonLimpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonEditar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/imgBotonGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImpresionLayout = new javax.swing.GroupLayout(panelImpresion);
        panelImpresion.setLayout(panelImpresionLayout);
        panelImpresionLayout.setHorizontalGroup(
            panelImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImpresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImprimirRetencion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );
        panelImpresionLayout.setVerticalGroup(
            panelImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImpresionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar)
                        .addComponent(btnEditar)
                        .addComponent(btnGuardar))
                    .addComponent(btnImprimirRetencion))
                .addContainerGap())
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Retención", "Emisión", "Numero", "Monto", "NIT", "ID Compra", "Pago", "Datos", "Guia", "Envio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalle);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String resultado = retencion.insertarRetencion(obternerObjetoRetencion(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        mensaje.manipulacionExcepciones("informacion", resultado, "Guardar Retencion");
        if(resultado.equals("Operacion realizada con exito.")) {
            String condicion = " where numero_retencion = '" + txtNumero.getText() + "'";
            objetosRetencion = retencion.buscarRetencion(condicion, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            txtIdRetencion.setText(String.valueOf(objetosRetencion.getId_retencion()));
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarPantalla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String resultado = retencion.actualizarBonificacion(obternerObjetoRetencion(), Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
        mensaje.manipulacionExcepciones("informacion", resultado, "Actualizar Retencion");
        btnGuardar.setEnabled(true);
        limpiarPantalla();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNumeroActionPerformed
        buscarRegistrosGuardados("Numero");
    }//GEN-LAST:event_btnBuscarNumeroActionPerformed

    private void btnBuscarIdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdCompraActionPerformed
        buscarRegistrosGuardados("ID Compra");
    }//GEN-LAST:event_btnBuscarIdCompraActionPerformed

    private void btnBuscarNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNITActionPerformed
        buscarRegistrosGuardados("NIT");
    }//GEN-LAST:event_btnBuscarNITActionPerformed

    private void tblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMouseClicked
        btnGuardar.setEnabled(false);
        limpiarPantalla();
        try {
            txtIdRetencion.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 0).toString());
            txtFechaEmsion.setDate(ConvertirDate(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 1).toString()));
            txtNumero.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 2).toString());
            txtMonto.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 3).toString());
            txtNit.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 4).toString());
            txtIdCompra.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 5).toString());
            txtFechaPago.setDate(ConvertirDate(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 6).toString()));
            txtDatos.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 7).toString());
            txtGuia.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 8).toString());
            txtFechaEnvio.setDate(ConvertirDate(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 9).toString()));
        } catch (Exception Error) {

        }
    }//GEN-LAST:event_tblDetalleMouseClicked

    private void btnImprimirRetencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRetencionActionPerformed
        if(txtIdRetencion.getText().isEmpty()) {
            mensaje.manipulacionExcepciones("critico", "No se puede mostrar el reporte porque no esta guardado el registro.", "Reporte Retencion");
        } else {
            imprimirReporte();
        }
    }//GEN-LAST:event_btnImprimirRetencionActionPerformed

    public void imprimirReporte() {
        //ejecución del repote seleccionado
        try{
            
            AccesoInventario acceso_inventario = new AccesoInventario();
            AccesoSucursal acceso_sucursal = new AccesoSucursal();
            ObjetosSucursal objeto_sucursal = new ObjetosSucursal();
            
            URL url_reporte = this.getClass().getResource("/inventory/reportes/rptRetencion.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();
            
            //parametros generales del encabezado
            objeto_sucursal = acceso_sucursal.buscarSucursales(1, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
            
            //parametros del reporte
            parametro.put("P_DIRECCION_SUCURSAL", objeto_sucursal.getDireccion_sucursal());
            parametro.put("P_NIT", objeto_sucursal.getNit_sucursal());
            parametro.put("P_NOMBRE_EMPRESA", objeto_sucursal.getNombre_sucursal());
            parametro.put("P_SUCURSAL", objeto_sucursal.getDescripcion_sucursal());
            parametro.put("P_TELEFONO", objeto_sucursal.getTelefonos_sucursal());
            
            //parametro de busqueda
            parametro.put("P_ID_RETENCION", Integer.parseInt(txtIdRetencion.getText().trim()));
            
            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso_inventario.conectar());
            JInternalFrame ventana = new JInternalFrame("Inventory 3.0");
            ventana.getContentPane().add(new JRViewer(pantalla));
            ventana.setPreferredSize(new Dimension(900, 500));
            ventana.setClosable(true);
            ventana.setMaximizable(true);
            ventana.setResizable(true);
            ventana.setVisible(true);
            ventana.pack();
            
            int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
            int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
            int x  = (ancho  - ventana.getWidth() ) / 2;
            int y  = ( alto - ventana.getHeight() - 100 ) / 2;
            
            Inventory.pnlPrincipal.add(ventana);
            
            ventana.setLocation(x, y);
            ventana.setVisible(true);
            ventana.toFront();
            
        } catch (JRException error) {
            mensaje.manipulacionExcepciones("critico", error.getMessage(), "Reporte de Anticipo Cliente");
        }
    }
    
    private void buscarRegistrosGuardados(String tipo) {

        DefaultTableModel tabla = new DefaultTableModel();
        ArrayList<ObjetosRetencion> listado = new ArrayList<>();
        agregarLog(tipo);
        
        //validare el campo de busqueda
        if (tipo.equals("Numero")) {
            agregarLog("Buscando información sobre el Numero de Retencion");
            if(txtBuscarNumero.getText().isEmpty() || txtBuscarNumero.getText().equals("")) {
                mensaje.manipulacionExcepciones("informacion", "Por favor ingrese el Numero a buscar.", "Buscar Numero Retencion");
            } else {
               String buscarNumero = txtBuscarNumero.getText().trim();
                agregarLog("Buscando los datos para el Numero " + buscarNumero);
                listado = retencion.seleccionarRetencion("numero_retencion = '" + buscarNumero + "'", Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText()); 
            }
        } else {
            if (tipo.equals("ID Compra")) {
                if (txtBuscarIdCompra.getText().isEmpty() || txtBuscarIdCompra.getText().equals("")) {
                    mensaje.manipulacionExcepciones("informacion", "Por favor ingrese el ID Compra a buscar.", "Buscar Compra Retencion");
                } else {
                    String buscarCompra = txtBuscarIdCompra.getText().trim();
                    agregarLog("Buscando los datos para la Compra " + buscarCompra);
                    listado = retencion.seleccionarRetencion("id_compra = " + buscarCompra, Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                }
            } else {
                if (tipo.equals("NIT")) {
                    if (txtBuscarNIT.getText().isEmpty() || txtBuscarNIT.getText().equals("")) {
                        mensaje.manipulacionExcepciones("informacion", "Por favor ingrese el NIT a buscar.", "Buscar NIT Retencion");
                    } else {
                        String buscarNit = txtBuscarNIT.getText().trim();
                        agregarLog("Buscando los datos para el NIT " + buscarNit);
                        listado = retencion.seleccionarRetencion("nit_retencion = '" + buscarNit + "'", Inventory.lblUsuario.getText(), Inventory.lblTerminal.getText());
                    }
                }
            }
        }
        
        if(listado.isEmpty()) {
            mensaje.manipulacionExcepciones("informacion", "No se encontraron datos.", "Listado Vacio");
        } else {
            tabla.addColumn("ID Retencion");
            tabla.addColumn("Emision");
            tabla.addColumn("Numero");
            tabla.addColumn("Monto");
            tabla.addColumn("NIT");
            tabla.addColumn("ID Compra");
            tabla.addColumn("Pago");
            tabla.addColumn("Datos");
            tabla.addColumn("Guia");
            tabla.addColumn("Envio");
            int n = 1;
            int y = 0;
            for(ObjetosRetencion x : listado) {
                tabla.setRowCount(n);
                tabla.setValueAt(x.getId_retencion(), y, 0);
                tabla.setValueAt(x.getFecha_emision_retencion(), y, 1);
                tabla.setValueAt(x.getNumero_retencion(), y, 2);
                tabla.setValueAt(x.getMonto_retencion(), y, 3);
                tabla.setValueAt(x.getNit_retencion(), y, 4);
                tabla.setValueAt(x.getId_compra(), y, 5);
                tabla.setValueAt(x.getFecha_pago_retencion(), y, 6);
                tabla.setValueAt(x.getDatos_pago_retencion(), y, 7);
                tabla.setValueAt(x.getGuia_retencion(), y, 8);
                tabla.setValueAt(x.getFecha_envio_retencion(), y, 9);
                y++;
                n++;
            }            
        }
        tblDetalle.setModel(tabla);
    }

    private ObjetosRetencion obternerObjetoRetencion() {
        
        try {
            
            if(txtIdRetencion.getText().isEmpty() || txtIdRetencion.getText().equals("")) {
                objetosRetencion.setId_compra(0);
            } else {
                objetosRetencion.setId_retencion(Integer.parseInt(txtIdRetencion.getText()));
            }
            
            if (txtFechaEmsion.getDate() == null) {
                objetosRetencion.setFecha_emision_retencion("NULL");
            } else {
                String fechaEmision = (txtFechaEmsion.getDate().getYear() + 1900) + "-" + (txtFechaEmsion.getDate().getMonth() + 1) + "-" + txtFechaEmsion.getDate().getDate();
                objetosRetencion.setFecha_emision_retencion(fechaEmision);
            }
            
            objetosRetencion.setNumero_retencion(txtNumero.getText());
            objetosRetencion.setMonto_retencion(Double.parseDouble(txtMonto.getText()));
            objetosRetencion.setNit_retencion(txtNit.getText());
            objetosRetencion.setId_compra(Integer.parseInt(txtIdCompra.getText()));
            
            if (txtFechaPago.getDate() == null) {
                objetosRetencion.setFecha_pago_retencion("NULL");
            } else {
                String fechaPago = (txtFechaPago.getDate().getYear() + 1900) + "-" + (txtFechaPago.getDate().getMonth() + 1) + "-" + txtFechaPago.getDate().getDate();
                objetosRetencion.setFecha_pago_retencion(fechaPago);
            }
            
            String datos = txtDatos.getText().replaceAll("'", "´").toUpperCase();
            objetosRetencion.setDatos_pago_retencion(datos);
            objetosRetencion.setGuia_retencion(txtGuia.getText());
            
            if(txtFechaEnvio.getDate() == null) {
                objetosRetencion.setFecha_envio_retencion("NULL");
            } else {
                String fechaEnvio = (txtFechaEnvio.getDate().getYear() + 1900) + "-" + (txtFechaEnvio.getDate().getMonth() + 1) + "-" + txtFechaEnvio.getDate().getDate();
                objetosRetencion.setFecha_envio_retencion(fechaEnvio);
            }
            
        } catch(Exception Error) {
            mensaje.manipulacionExcepciones("critico", "No se puedo almacenar los datos en el objeto.", "Error crear objeto");
            agregarLog(Error.toString());
        }
        return objetosRetencion;
    }
    
    private void limpiarPantalla() {
        txtIdRetencion.setText("");
        txtNumero.setText("");
        txtNit.setText("");
        txtFechaEmsion.setDate(null);
        txtMonto.setText("");
        txtIdCompra.setText("");
        txtFechaPago.setDate(null);
        txtGuia.setText("");
        txtFechaEnvio.setDate(null);
        txtDatos.setText("");
    }
    
    private void agregarLog(String texto) {
        this.Log = this.Log + "G. PROVE." + ": " + texto + " \n";
        Inventory.txtLog.setText(Log);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarIdCompra;
    private javax.swing.JButton btnBuscarNIT;
    private javax.swing.JButton btnBuscarNumero;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimirRetencion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelImpresion;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtBuscarIdCompra;
    private javax.swing.JTextField txtBuscarNIT;
    private javax.swing.JTextField txtBuscarNumero;
    private javax.swing.JTextField txtDatos;
    private com.toedter.calendar.JDateChooser txtFechaEmsion;
    private com.toedter.calendar.JDateChooser txtFechaEnvio;
    private com.toedter.calendar.JDateChooser txtFechaPago;
    private javax.swing.JTextField txtGuia;
    private javax.swing.JTextField txtIdCompra;
    private javax.swing.JTextField txtIdRetencion;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
